### ISSUE TITLE
reconsider the grid

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#10]
How many people actually print out maps and use the New Israel Grid anymore?
IMO just another cluttering element.

**Comment by HarelM** [comment]
I strongly disagree, I don't printout the map but the grid helps me to know what size of area I'm looking at and how long is the trail I want to do/how many kms there are until the end.

**Comment by valleyofdawn** [comment]
You already have the scale bar for that. 
and if this is the only use, you can remove the coordinates on the grid.

**Comment by HarelM** [comment]
The scale bar belongs to the site not the map and it does not serve my needs anyway. I don't see much use to the coordinates as well, but I'm guessing it's there for a reason.

**Comment by valleyofdawn** [comment]
The apps you're likely to use the map with (i.e OruxMaps, Locus) have a scale bar of their own.

**Comment by HarelM** [comment]
As I said, the scale does not serve my needs, no matter which app I use.

**Comment by zstadler** [comment]
I agree with Harel. Knowing what's 1 Km improves my orientation.
