### ISSUE TITLE
Incorrect mapping and interpretation

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#101]
I have looked at the Galed intermittent reservoir and saw that it was incorrectly mapped as far as I can understand - there's no definition for intermittent to reservoirs:
http://wiki.openstreetmap.org/wiki/Key:intermittent
I have added seasonal=winter but when looking at the rules files I saw that it was not taken into account.
Here's the definition of seasonal:
http://wiki.openstreetmap.org/wiki/Key:seasonal
What do you think? Currently I left both of them until we decide.

**Comment by zstadler** [comment]
The [intermittent tag](http://wiki.openstreetmap.org/wiki/Key:intermittent) can also be applied to water bodies:

> The tag intermittent=yes is used to indicate that a waterway (river, stream, etc.) does not have a permanent flow.

> Or that a water body (lake) is not permanently filled with water. 

The seasonal key could be added to the rules that use intermittent. However, there are currently only 3 ways in Israel with a seasonal tag, all of which are also tagged as intermittent.

P.S., I don't know the sources of this reservoir. It may or may not be filled with reclaimed water, not necessarily during the winter.

**Comment by HarelM** [comment]
Missed that part of the sentence, sorry.
Wouldn't hurt to add it to our rules in case someone uses it in the future.
