### ISSUE TITLE
MTB IL: work out labels for relations

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#103]
Many MTB relations have names but the paths they are composed of do not.
It would be nice if there was a way to show those.

**Comment by HarelM** [comment]
I don't think this is an issue to the map, I think it should be fixed in OSM database.
Overpass query maybe able to help you, I may be able to create a list for you if you need one.

**Comment by zstadler** [comment]
I beg to differ.

The names are in OSM, copying tags from a relation to its members is IMHO a bad idea as the same member can also be a member of other relations. For example, should a section be named after the local bicycle route or the regional hiking route when it is a member of both!?

Which brings me to a question about the requested behavior of this issue: Which name to put on a relation that belongs to several bicycle routes/relations?

**Comment by zstadler** [comment]
@valleyofdawn,
Do you plan to address this issue in the vector maps #93?
Can we close this issue?

**Comment by zstadler** [comment]
The repository is not actively maintained after the transition to vector maps.
