### ISSUE TITLE
Non-incremental map builds

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#110]
With Incremental Tile updates #108 deployment as default, there is a need to allow non-incremental map builds.

Non-incremental map builds are done when the `Cache` directory does not contain the `latest` pbf file.
In such a case, the latest map data is downloaded from the incremental updates server. 

Incremental map updates will be automatically used after all maps are successfully-built non-incrementaly.

**Comment by HarelM** [comment]
Another use case for this will be to allow a once in a while "fresh start" if for any reason there are issue with the incremental tile updates, kind of reset button.

**Comment by zstadler** [comment]
Non-incremental tile generation is activated when no "latest" pbf file exists.
In addition, non-incremental tile generation is resumed until a successful completion. Only then will incremental tile generation be activated.
