### ISSUE TITLE
Increase frequency of incremental map updates

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#111]
With Incremental Tile updates #108, the maximal map update frequency is daily, as defined by the update frequency at [download.geofabrik.de](http://download.geofabrik.de/)

[download.openstreetmap.fr](http://download.openstreetmap.fr/) offers minutely diffs which allow increasing the frequency of the map updates as well as reducing the lag between a map edit and its reflection at the site.

Note: The [download.openstreetmap.fr](http://download.openstreetmap.fr/) extraction is done separately for Israel and Palestine.

**Comment by zstadler** [comment]
There were a few issues with the download.openstreetmap.fr
* The Israel diffs contain deletions for ways that are still present in the Palestine area, and vice versa. As a result, merging the diffs caused incorrect deletions in both areas.
    Solution: download.openstreetmap.fr were kind to provide diffs and extracts for the joint israel_and_palestine area.
* The israel_and_palestine extract was missing OSM objects. Specifically, a map user noticed that road 3866 near Nes Harim ([way 442264646](https://www.openstreetmap.org/way/442264646)) is missing. AFAIK, the root cause is that way 442264646 is missing from the asia extract, and subsequently it's missing from the israel_and_palestine extract. An e-mail was sent to the download.openstreetmap.fr team.
  Workaround: israel_and_palestine data was extracted from Geofabric's Asia extract using the israel_and_palestine polygon from download.openstreetmap.fr. Unfortunately, this extraction had to be done on a Linux (virtual) machine because of limitations of osmconvert.
  Solution: TBD

**Comment by zstadler** [comment]
When the map is updates, DB updates for the search and routing services should be done. The update must be run as administrator using the ```runas``` command:
```
runas.exe /savecred /user:administrator "..."
```

**Comment by HarelM** [comment]
I have added the log file for the updater, I don't see that it's currently running besides at the scheduled time (05:04).

**Comment by zstadler** [comment]
That's why this issue is not closed yet.

**Comment by zstadler** [comment]
It seems like everything is working fine.
