### ISSUE TITLE
Move guidepost icon up

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#112]
Can you move the guidepost icon up and right so that its leg will represent its location (currently the center of the icon represent the guidepost location which doesn't look so good):
for example in the below picture the leg of the guidepost should be on the road fork 
![image](https://cloud.githubusercontent.com/assets/3269297/20869870/e27a9fa4-ba84-11e6-8345-1f9ba0fb2a1f.png)

**Comment by zstadler** [comment]
A link to the location of the above example will be highly appreciated

**Comment by HarelM** [comment]
Here you go:
http://israelhiking.osm.org.il/#/19/31.4689/35.3889

**Comment by HarelM** [comment]
I think it's still not in the right place, unless the tiles have not been generated yet?

**Comment by zstadler** [comment]
The tiles were not updated yet
