### ISSUE TITLE
Locus offline download issues

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#119]
Hi,

Please update Locus offline xml files for the Hebrew version to the new OruxMaps folder under Hebrew folder.
Please add English Locus xml files pointing to the relevant location.

P.S. Maybe we should rename it to ```OfflineFiles``` or something that is not OruxMaps specific since Locus can use it now and off-road will be able to use it in the future, we won't change the original OruxMaps folder name, just those under the specific language...?

**Comment by zstadler** [comment]
Locus XML file will be moved to a ```Locus``` directory.
The ```OruxMaps``` directory will only contain maps in OruxMaps format.
Both ```Hebrew``` and ```English``` will have  ```Locus``` and ```OruxMaps``` directories.
If we decide in the future to provide other file formats and/or application-specific files it will be done in their own directories.

**Comment by HarelM** [comment]
Sure thing. Please let me know when this will be available so I can change the code accordingly.

**Comment by zstadler** [comment]
The Locus Map files are available for testing at
http://israelhiking.osm.org.il/Hebrew/LocusMap/
and 
http://israelhiking.osm.org.il/English/LocusMap/

Please let me know when you're done so I can remove the old files and update the repository.

**Comment by HarelM** [comment]
Would you like to change the code yourself?
Code can be found here:
https://github.com/IsraelHikingMap/Site/blob/master/IsrealHiking.Web/controllers/InfoController.ts
under ```getDownloadUrl``` funciton.
Let me know what you decide, I can do it tonight. your call.

**Comment by zstadler** [comment]
I will not be able to do that today.
While you're at it, you may switch the download from http to https.

**Comment by HarelM** [comment]
I Will, no problem, please update the locus xml files as well from http to https.

**Comment by zstadler** [comment]
Done

**Comment by HarelM** [comment]
Updated client code as well, I think you can close the issue.
