### ISSUE TITLE
Allow access to the oruxmaps folder to download the .db file

### ISSUE THREAD

**Issue by ilanza** [IsraelHikingMap/Map#127]
Currently application providers are required to download a zip file and then to extract it on the device. This requires the device to have free storage of twice the size of the maps. E.g for level 16 the user is required to have 4.5 Gb free. 
If you will allow us to download the orux db files it will solve it.

Thanks.

**Comment by zstadler** [comment]
The 8 OruxMaps offline files will be available at
```IsraelHiking.osm.org.il/<Hebrew|English>/Oruxmaps/Israel <Hiking|MTB>[ 16]/```

Each directory has 2 files:
* ```OruxMapsImages.db```
* ```Israel <Hiking|MTB>.otrk2.xml``` according to the directory name
