### ISSUE TITLE
Display of the statistics graph

### ISSUE THREAD

**Issue by Eli-Leshem** [IsraelHikingMap/Map#130]
The graph is over the map and not clear. 

Suggestions:

- Add a transparency adjustment
- Enable to move the graph window out of the main window.

 Thanks,

**Comment by HarelM** [comment]
Closing this in favor of: https://github.com/IsraelHikingMap/Site/issues/341
This repository is for map issues (how the map looks, features on the map etc while the other is related to the web application that allows "playing" with the map)
