### ISSUE TITLE
Numbers and parentheses mishandeled in Hebrew name tags

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#135]
See
[גבעת חיים (איחוד)](https://israelhiking.osm.org.il/#!/16/32.4003/34.9330)
[אהוד 10](https://israelhiking.osm.org.il/#!/16/32.5658/35.0038)

**Comment by zstadler** [comment]
Some starting points:
* http://stackoverflow.com/questions/3856403/right-to-left-languages-in-python
* https://www.microsoft.com/middleeast/msdn/control.aspx

**Comment by zstadler** [comment]
Current fixes should be prקeverved. For example:

['ביר הדאג](https://israelhiking.osm.org.il/#!/15/31.0259/34.7028)

**Comment by HarelM** [comment]
Also for [גבעת חרוט](https://israelhiking.osm.org.il/#!/17/30.6183/34.9467)

**Comment by zstadler** [comment]
Addressed as part of #93.

Note that some of the above examples were a result of "[tagging for the renderer](https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer)" that aimed to "fix" the problem as was shown on openstreetmap.org and other sites.
