### ISSUE TITLE
Adjusting the MTB map rules  to work in urban areas

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#136]
Initial ideas:
Color-code city streets by maximum speed
Hide buildings below residential area and  elevation contours
Lose restaurant names
Hide construction site icons below a certain size

**Comment by citizen-dror** [comment]
Maybe we can learn from OSM?
[](https://www.openstreetmap.org/#map=12/50.0909/14.5294&layers=C)
2.	main cycle routs – in strong purple (area route) or blue  (local)
In higher zoom – (12 or 13 level till 1)
https://israelhiking.osm.org.il/#!/12/32.0984/34.8843
in close zoom – same base colors but more transparent and wide  
3.	Main roads for cars – in pastel /soft colors of light-blue , soft green, soft yello-orange – you should see them but they are not the main issue.
https://www.openstreetmap.org/#map=13/50.1066/14.6285&layers=C
4.	Is there a way to group icons middle zoom ? it will be a good way to hide restaurants and other small features which are important in a rural area but disturb in urban map.

**Comment by citizen-dror** [comment]
Construction site icons  - insted of show at zoom 15, show at 16 or 17

**Comment by valleyofdawn** [comment]
Do you mean OpenCycleMap?
There is no way to group the icons on the mdp itself.

**Comment by valleyofdawn** [comment]
Following discussion. Designate urban areas and tag the following features within them for hiding:

Cafes
Restaurants
Construction sites
Archeological sites
Places of worship
Parking areas
Gates
Supermarkets
Buildings?

Add features:
Safe roads
Dangerous roads
Hills?
Tel-Ofan   ##points?

**Comment by valleyofdawn** [comment]
Cities in the list? Dror?

**Comment by citizen-dror** [comment]
Tel aviv for start

later
Teal aviv, Ramat gan, givatim, Holon, Bat-yam, bnay brak, Peatch Tikva,
Ramat Hasharon, Herzlia, Kfar saba, Ranna,
Rishon letaion , nesziona, rechovot,

Jerualem, Ashdod, Ashkelon, ber shava, ntanya, nahria,

2017-07-03 12:45 GMT+03:00 valleyofdawn <notifications@github.com>:

**Comment by zstadler** [comment]
You may use [this query](http://overpass-turbo.eu/s/q8T) to find residential ways that do not have a `maxspeed=30` tag.
Pan, zoom and press "Run" to see the results for different areas.

In order to see the results on top of the Israel Biking Map, please put
`//israelhiking.osm.org.il/English/mtbTiles/{z}/{x}/{y}.png` in
Settings &rarr; Map &rarr; Tile server:

![image](https://user-images.githubusercontent.com/1304610/27793127-688c7704-6005-11e7-9c09-618059eef50f.png)

**Comment by valleyofdawn** [comment]
What is the "in-city" tag going to be?  I want to start playing with the rules file.

**Comment by valleyofdawn** [comment]
A simpler solution for looking at max speeds is the layer on this map layer which color-codes roads based on their max speed.

[https://israelhiking.osm.org.il/#!/?s=R1SV42nsB1](https://israelhiking.osm.org.il/#!/?s=R1SV42nsB1)

**Comment by citizen-dror** [comment]
great tool !
i used it to max speed most of the roads between arlozerov and the yarkonn
river,
http://overpass-turbo.eu/s/qaK

a "living street" lilke HaRav Friedma
<http://www.openstreetmap.org/#map=18/32.09418/34.79316&layers=C>n is by
low and Patrice 30 km street - so we don't have to add to it 30 max limit
tag it shod be added also to 30 km residentials



2017-07-04 14:33 GMT+03:00 valleyofdawn <notifications@github.com>:

**Comment by zstadler** [comment]
The plan is for UrbanTags.py script will add a "_urban"="yes" tag to nodes, ways, and relations with "amenity", "barrier", "building", "construction", "highway", or "historic" tags.

Comments?

**Comment by valleyofdawn** [comment]
Construction can be land_use too. urban or _urban?

**Comment by zstadler** [comment]
Will add "landuse" tagged elements.

The use of "_urban" is intentional in order to distinguish between our generated tags and potential OSM tags.

**Comment by citizen-dror** [comment]
i maped most of tel aviv - 30 max speed areas (excpect Zahala and some
areas in the south )


2017-07-04 20:15 GMT+03:00 zstadler <notifications@github.com>:

**Comment by HarelM** [comment]
@citizen-dror Forgot to send you the relevant repository about the routing, here it is:
https://github.com/graphhopper/graphhopper
Look for for flag encoder classes for the relevant algorithm.

**Comment by valleyofdawn** [comment]
I uploaded my draft of an urbanized map to branch [ https://github.com/IsraelHikingMap/Map/tree/MTB-IL-Guy-new](url).
Please check it out before I merge it.

**Comment by valleyofdawn** [comment]
![image](https://user-images.githubusercontent.com/689201/28322006-85f89c94-6bdd-11e7-8de5-ab58fa370825.png)
