### ISSUE TITLE
Rendering issues (apparently depth)

### ISSUE THREAD

**Issue by SwiftFast** [IsraelHikingMap/Map#137]
http://israelhiking.osm.org.il/#!/18/32.6855/35.0791

3 buildings are green due to being near a national park boundary.

http://israelhiking.osm.org.il/#!/17/32.6831/35.0871

Name rendering below a way.

**Comment by HarelM** [comment]
Can you add a screen shot, I don't see an issue with building being green - the green part in the below screenshot is grass.
Also it will be better to open two separate issue since what you describe is two unrelated bugs.
I don't see the name below a way bug though:
![image](https://user-images.githubusercontent.com/3269297/27002113-82b216d8-4de1-11e7-9bd0-f16f3128b13e.png)

**Comment by SwiftFast** [comment]
This is not the place I sent. And the fact that you saw a different place could be #138. I will provide a screenshot.

**Comment by SwiftFast** [comment]
>Also it will be better to open two separate issue since what you describe is two unrelated bugs.

I don't know the code and you might be right, but both seem to me nearly identical depth tuning issues. Case 1, buildings render below boundary. Case 2, ways render above text.

**Comment by SwiftFast** [comment]
![1](https://user-images.githubusercontent.com/28669244/27003768-a34a0940-4e05-11e7-8af6-a4251471e72d.png)

![screenshot from 2017-06-10 17-52-09](https://user-images.githubusercontent.com/28669244/27003769-a6265cae-4e05-11e7-9976-f802cbd3c25c.png)

![2](https://user-images.githubusercontent.com/28669244/27003770-a791ac06-4e05-11e7-940c-7fc0e5806174.png)

Here are the images. To locate the place,  you can use the coordinates in the first post, or search for "מצפור טייסת העמק". The buildings are slightly west of the Metspor.

**Comment by HarelM** [comment]
Can you make a screen shot of the right layers pane? The second issue might be because you have the ihm trails overlay enabled...?

**Comment by SwiftFast** [comment]
>Can you make a screen shot of the right layers pane? The second issue might be because you have the ihm trails overlay enabled...?

You're right! It was enabled. My bad. The building issue remains, though.

As an aside UX note, I see no point in *allowing* that layer to be enabled when the "מפת הטיולים הפתוחה" is enabled.

**Comment by HarelM** [comment]
> As an aside UX note, I see no point in allowing that layer to be enabled when the "מפת הטיולים הפתוחה" is enabled.

I agree, It's not an elegant or easy fix though.

I'm not sure there's something we can do with the buildings since we decided it's important to see the end of the natural reserve more than seeing the building, keeping this issue open though since I agree it's a problem.

**Comment by zstadler** [comment]
Extending on @HarelM above, the wider part of the Nature Reserve's boundary is semi-transparent in order to keep other map elements visible. In fact, it seems to work since you understood that there was an overlap of the boundary with buildings.

Would you prefer that buildings and potentially other map elements would hide Nature Reserves' boundaries?

**Comment by SwiftFast** [comment]
> it seems to work since you understood that there was an overlap of the boundary with buildings.

Some buildings are totally green and look as if they're a different feature. (see bottom right building in first picture). I believe buildings should be rendered above the the boundary. Or maybe: Boundary's outermost line renders above buildings, but the boundary's "inner shade" renders below. If that's technically possible.

Regardless, there's no serious confusion and this is a minor and low priority issue.
