### ISSUE TITLE
Map not always zooming to the proper area, hashbang issues?

### ISSUE THREAD

**Issue by SwiftFast** [IsraelHikingMap/Map#138]
When I open, one of these links, then close it and open the other, the map sometimes zooms to the location that was just closed, and not to where it's supposed to be. 

http://israelhiking.osm.org.il/#!/18/32.6855/35.0791

http://israelhiking.osm.org.il/#!/17/32.6831/35.0871

Firefox 45 ESR.

**Comment by HarelM** [comment]
Sorry for nagging, but this repository is for rendering issues of the map and tiles.
For issues related to Site such as the above please use the following repository:
https://github.com/IsraelHikingMap/Site/issues

**Comment by SwiftFast** [comment]
No problem. You're completely right.
