### ISSUE TITLE
basic keyboard navigation should work (arrow panning and zooming)

### ISSUE THREAD

**Issue by hesher** [IsraelHikingMap/Map#143]
Leaflet maps are usable with a keyboard by default (check out http://leafletjs.com/)
For some reason, this functionality was removed for Israel Hiking Map.

It should be un-removed :)

**Comment by HarelM** [comment]
Thanks for reporting this issue!
Please note that this is the wrong repository to report it though.
Can you please move this issue to the site repository?

**Comment by hesher** [comment]
oops. sure.
