### ISSUE TITLE
Add icon for cemetery in IHM map

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#145]
Although the following issues discuss this, I still think cemeteries should be marked with an icon.
#34 #61
I think it does exists in MTB, but the following has an order issue:
https://israelhiking.osm.org.il/#!/19/32.5953/35.0610

**Comment by zstadler** [comment]
Please explain why you think cemetery icons should be added to the Hiking map.

Please open a separate issue for the order problem in the MTB map.

**Comment by HarelM** [comment]
A cemetery help you know where you are. In current style it's hard to see if a place is a cemetery or not. I wanted to start a hike from near a cemetery and wasn't sure I was in the right place since I didn't understand from the map I'm supposed to start near a cemetery.
I understand why the name can create clutter but a small icon would help a lot.

**Comment by zstadler** [comment]
Most of the OSM elements that can help you know where you are. We don't show most of them.

**Comment by HarelM** [comment]
I think its representation is too subtle now, you can hardly see it, and in most non urban places this place is very beautiful and worth visiting.

**Comment by zstadler** [comment]
A POI DB, like AmudAnan, will be more appropriate for this usage.

The map has gone through a cleanup phase, and may need additional clean-ups. Any addition needs to have a strong justification, which I don't think was provided here.

**Comment by HarelM** [comment]
I respectfully disagree. POI DB can used in sites but not in other places that may user the map like navigation apps.
A single icon for every cemetery used in maximum zoom should not clutter the map much and would be very helpful IMO.
I found this to be relevant when hiking and for orientation and interesting places no less than ruins and archaeological site. I'm not sure what you define as strong justification. I strongly feel about this.

**Comment by valleyofdawn** [comment]
Just as a side note, the reason I added cemeteries to the MTB map is that they often contain accessible **drinking water** taps at good quality. Playgrounds were added for the same reason.

**Comment by HarelM** [comment]
Any updates on this? 
I'm looking for a consensus, but I don't mind adding it if we can't agree.

**Comment by zstadler** [comment]
I don't want this addition. Cemeteries are not a recreational attraction and drinking water is shown wherever mapped.

**Comment by HarelM** [comment]
Yay! 😊😊😊
