### ISSUE TITLE
Bad cemetery icon order in MTB map

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#146]
Split of #145
https://israelhiking.osm.org.il/#!/19/32.5953/35.0610

![image](https://user-images.githubusercontent.com/3269297/27918097-973f3974-6276-11e7-95f7-f364c90d9ff2.png)

**Comment by valleyofdawn** [comment]
Thanks, will be corrected on next release.

**Comment by HarelM** [comment]
Can you please link the relevant commit?
