### ISSUE TITLE
New approach for overlay maps

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#147]
Currently, the trails layer is created by a separate rules file that need to be updated manually after relevant changes in the full map.

Instead, we can use the same file and filter the OSM data file and keep just the features that are needed in the overlay.

Potentially, the map background can be changed using Maperitive or Maperipy commands.

**Comment by zstadler** [comment]
[Osmfilter] https://wiki.openstreetmap.org/wiki/Osmfilter) may be able to do the work

**Comment by HarelM** [comment]
Can't the same be achieved with python code? how is this any different from other manipulations we are doing on the data?

**Comment by zstadler** [comment]
As far as modifying the OSM data, the existing Python code adds tags to existing elements or created a new .osm file in order to add new entities. It does not filter or delete data.

The OSM data modifications and comparisons needed for the incremental tile updates is done using external programs. Similarly in this case, I do not want to re-invent the wheel.

**Comment by HarelM** [comment]
I understand your point, although you'll still need to write the filtering conditions - it's not about reinventing the wheel it's the same logic no matter where you'll write it... 
In any case I'm not sure it will easier to filter the data before loading it to maperitive rather then filtering it after loading with python, but whatever you think will be easier to write and maintain works for me. Just wanted to make sure we thoroughly consider the pros and cons before adding another third party. :-)

**Comment by zstadler** [comment]
The current equivalent of the filtering conditions is the few definitions that are currently used in the trails rules file, for example is `-keep="highway and colour"` for osmfilter.

That's hardly "reinvention". It is reducing the rules file to the essential difference between the full map and the trails overlay.

**Comment by HarelM** [comment]
Not sure I understand your last comment, in any case I trust your judgment.
