### ISSUE TITLE
Add copyright text to the generated tiles

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#148]
See https://stackoverflow.com/a/23180764 on inserting text to png files
See http://braincrunch.tumblr.com/post/22037453467/maperipy-sample-generate-tiles-and-then-optimize on post-processsing Maperitive tiles

**Comment by SwiftFast** [comment]
Does this mean there'll be text on each and every tile on the map?  It sounds a bit unaesthetic.

**Comment by SwiftFast** [comment]
My bad. This seems to be about metadata.

**Comment by HarelM** [comment]
Where does one will see this copyright notice?
