### ISSUE TITLE
Change the upload directory of lastmodified.js file from "js" folder to "scripts" folder

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#15]

**Comment by HarelM** [comment]
The best solution is to "touch" the index.html file and avoid all this mess, I would prefer it if possible as the script is looking at this file by default (if lastmodified.js is not present).

**Comment by zstadler** [comment]
"touching" sets the date according to the date of the upload, while we want to show the date of the OSM data.

I prefer that the side contents will be based on contents of files rather than their metadata.

**Comment by HarelM** [comment]
I understand, just change the folder and open an issue in the site repository so that I'll remember to fix it...
