### ISSUE TITLE
Add gradient overlay

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#150]
Similar to [CalTopo](https://caltopo.com/l/2B1M)
<img width="249" src="https://user-images.githubusercontent.com/1304610/28643922-1d8e2ee2-7260-11e7-8d76-5c83b6df0854.png">

Compare with
<img width="271" src="https://user-images.githubusercontent.com/1304610/28643943-318127ce-7260-11e7-8976-c2dd8ae4cbfa.png">

[Maperitive custom shader](http://braincrunch.tumblr.com/post/26190799580/maperitive-alpenglow-effect-using-a-custom-shader) is a possible implementation approach.

**Comment by HarelM** [comment]
Since this doesn't change much I think we should only try and create this once and not add it to the map update process.

**Comment by zstadler** [comment]
Yes. This layer should be updated only when the DEM changes, just like the existing contours and hill-shading.

**Comment by zstadler** [comment]
The colors used in the map above:

|Slope| Color|
|-----|-----|
| 20° | [#00FF09 - rgb(0,255,9)](http://www.color-hex.com/color/00ff09)|
| 28° | [#F5FF0A - rgb(245,255,10)](http://www.color-hex.com/color/f5ff0a) |
| 40° | [#FF0000 - rgb(255,0,0)](http://www.color-hex.com/color/ff0000) |
| 55° | [#0000FF - rgb(0,0,255)](http://www.color-hex.com/color/0000ff) |
| 60° | [#0000FF - rgb(0,0,0)](http://www.color-hex.com/color/000000) |

**Comment by zstadler** [comment]
https://caltopo.blogspot.co.il/2013/01/slope-shading-revisited.html

**Comment by zstadler** [comment]
The repository is not actively maintained after the transition to vector maps.
