### ISSUE TITLE
Correct fill of inner portions in natural reserve relations

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#152]
Common to IHM and IMBM,
Still so not know why it happens.

**Comment by zstadler** [comment]
I can only see a problem with the nature reserve symbol in IMTB. For example:

![image](https://user-images.githubusercontent.com/1304610/28756044-e156f19e-756f-11e7-8a2c-582fef164827.png)

One symbol is placed in the center of the outer boundary of [relation 5941143](https://www.openstreetmap.org/relation/5941143) and another in the center of the inner boundary.

The fill in both maps is working fine.

**Comment by valleyofdawn** [comment]
In OHM the outer border appears but the inner does not.

**Comment by zstadler** [comment]
In IHM, the border decoration, inner or outer, is not working if the boundary is not a single way 

That's a different issue which is caused by the limitation of the Maperipy analysis code.

**Comment by zstadler** [comment]
By the way, the split of the inner boundary of relation 5941143 into 3 separate ways was a mapping error.
Fixed...

**Comment by zstadler** [comment]
Addressed as part of #93.
