### ISSUE TITLE
Update MTB legend

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#153]
**Additions:**
Stairs,
Low-speed streets
Dry riverbed
Residential road
Playground

**Corrections** (should point elsewhere)
Easy path  (should be green)
Area B
International border
supermarket
Toilet
Construction site
Peak would be nicer with ele, cave without

**Corrections** (should have different title)
מרכז מבקרים -> מידע

**Categories**
Move all paths (foot and bike) to one category, and all tracks to another. סינגלים/דאבלים

**Comment by zstadler** [comment]
This should be opened as a [Site issue](https://github.com/IsraelHikingMap/Site/issues)

In the new issue,
- Please differentiate between new MTB legend entries that already exist in the IHM, like stairs, and completely new entries, such as low-speed streets.
- For new entries, please define their group name, Hebrew title, English title, location (lat/lon), and zoom.
- For location changes please define their new location (lat/lon), and zoom.
- For title changes, please modify the Hebrew and/or English translation. (See https://github.com/IsraelHikingMap/Site/wiki/Adding-New-Text-and-Updating-the-Translations.)
- For new categories please define their Hebrew title and English title.
