### ISSUE TITLE
Better management of current maps' build state

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#155]
As a co-server developer I would like to be able to see the current state of the map build process so that I'd know what's currently running.
Here's a list of what I would like:
1. Be able to see which map update is currently running.
2. How much time did previous run took for each type of map.
3. Be able to stop a map update.
4. Be able to start a map update.
5. (Optional, but would be greatly appreciated) Be able to easily do it from a web interface or any other UI which is not command line.
6. Be able to look on a log of a map build.
7. Be able to see if there were any errors in a map build in a single place (not need to search many log files).

When trying to deeply think about it, the process of map updates is not so much different from the concept of a continues integration server where the product is map tiles.
I'm familiar with the [Jenkins](https://jenkins.io/) CI system and I think it facilitates all the above requirements.
There might be other CI systems as well that can do it, but I know Jenkins is widely used and has a lot of extensions.
I have used it briefly in my previous workplace and I think it's a good place to see the current state of the build system.

**Comment by zstadler** [comment]
The log files of the build process are giving all of the needed info.

**Comment by HarelM** [comment]
This is only one requirement of the specified above, please don't close this issue without at-least specifying how to do all the operations above.

**Comment by zstadler** [comment]
I want to close this issue.

A. The following items are covered by the log files which are available on the server:
- Be able to see which map update is currently running.
- How much time did previous run took for each type of map.
- Be able to look on a log of a map build.
- Be able to see if there were any errors in a map build in a single place (not need to search many log files).

B. Map update is not a service. The standard Windows tools, such as the task manager and the task scheduler, can be used to perform the following:
- Be able to stop a map update.
- Be able to start a map update.
- (Optional, but would be greatly appreciated) Be able to easily do it from a web interface or any other UI which is not command line.

 As far as I understand, the Map administration is as good or better than the Site administration.

**Comment by HarelM** [comment]
I do not know how to do all those operations.
One of the reasons for this issue is to document how to do them.
I really think you should experiment with Jenkins just for the sake of trying it out, maybe you'll find it useful, but that's only a suggestion.
I would enjoy a single place of admonition with a decent UI, but again, I don't like cmd stuff much...

**Comment by zstadler** [comment]
@HarelM,
Can we close this?

**Comment by HarelM** [comment]
Sure.
