### ISSUE TITLE
Barriers appear as gates

### ISSUE THREAD

**Issue by YGMZ** [IsraelHikingMap/Map#158]
Barriers appear as gates in IHM & in IMTBM.
See ראש מעלה חצרה and others as well.

**Comment by zstadler** [comment]
Thanks for the report. 

Can you please attach links to the locations or the OSM elements.

**Comment by YGMZ** [comment]
31.7889680, 35.1382241

**Comment by zstadler** [comment]
[Node 4049909258](https://www.openstreetmap.org/node/4049909258) is a debris barrier with no access to vehicles. Rendering barriers according to their access restrictions is covered by #159.

@YGMZ, I suggest you close this issue and we'll continue to address the broader barriers issue in #159.

**Comment by YGMZ** [comment]
covered by #159 - closed
