### ISSUE TITLE
Map seasonally lake + Add to legend

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#16]
Add some kind stripped blue area to seasonally water areas.

**Comment by zstadler** [comment]
I believe that if the area is tagged with intermittent=yes, the border will be made of dashes.

Please add a link to an example.

**Comment by HarelM** [comment]
I looked into the intermittent=yes.
I tagged an intermittent lake I know of here (just now so it shouldn't be in the map until next scheduled run):
http://osm.org.il/IsraelHiking/IsraelHikingMap.html#/16/32.5671/35.0666?baselayer=Israel_Hiking_Map&markers=&Route_1=
I think the filling should be dashed, not just the border...
Also we need to look for wadi tags and replace them with intermittent=yes as the wiki says we should not be using them:
http://wiki.openstreetmap.org/wiki/Tag:waterway%3Dwadi

**Comment by zstadler** [comment]
I don't like the dashed fill for the intermittent water areas, and reservoirs in particular.

The example at hand has two overlapping reservoirs:

https://www.openstreetmap.org/way/54638278
https://www.openstreetmap.org/way/54638279

so changing one of them is not enough...
Specifically, for this reservoir, I've never seen it empty. I believe at also accepts sewage...

P.S., Changing the map data and correcting the waterway=wadi tags is not a task for the map - ignored.

**Comment by HarelM** [comment]
Can you think of a reason to put two reservoirs at the same location? Isn't it a mistake?
In any case I've been there once when it was dry out, so I should know.
The sewage is going to the little one south west of this reservoir.
Can't you put a subtle dashed area?
Something like that (I did it in paint so it's very bad, but you get the point).
![intermittent](https://cloud.githubusercontent.com/assets/3269297/10564386/b2bc60aa-75ba-11e5-9d62-b8668dd30c8d.png)
Or if you don't like this one at least a thick border so a traveler will be able to know that the lake might not be there when he arrives... (true story...)

About the wadi: Let's make sure we support wadi and intermittent stream so that changing this will not affect us.

**Comment by zstadler** [comment]
I'll take a look at the proposal.

We support both wadies and intermittent streams.

**Comment by zstadler** [comment]
Legend update is next

**Comment by valleyofdawn** [comment]
Do we still have Wadi's in the Israeli OSM DB?

**Comment by zstadler** [comment]
I regularly correct them as part of my routing DB cleanup habit.

**Comment by zstadler** [comment]
Legend update is part of #36
