### ISSUE TITLE
Don't render archeological sites within a bigger site

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#162]
Archaeological sites such as Ovdat and Beit Govrin are full of small features. All of them are currently rendered on both maps and create a jumble.
Can we define an archaeological site relation and stop rendering the lesser sites, at least at lower zooms?

**Comment by zstadler** [comment]
@valleyofdawn 
Please see [this post](https://forum.openstreetmap.org/viewtopic.php?pid=598787#p598787) in the OSM Q&A forum for an example of using a relation.

[Ovdat](http://israelhiking.osm.org.il/#!/16/30.7941/34.7732) does not look good even in zoom 16.
![image](https://user-images.githubusercontent.com/1304610/30108381-cc8f5482-930a-11e7-887c-53811fc2da67.png)

In [Beit Guvrin](http://israelhiking.osm.org.il/#!/16/31.5922/34.8994) there seems to be issues with clusters of cave entrances, not archaeological sites
![image](https://user-images.githubusercontent.com/1304610/30108424-f824c244-930a-11e7-90bc-5eb2bc649b38.png)

[Tel Megiddo](http://israelhiking.osm.org.il/#!/16/32.5855/35.1841) now has a [site relation](https://www.openstreetmap.org/relation/7548260)
![image](https://user-images.githubusercontent.com/1304610/30112455-24ebf554-931a-11e7-94a2-7fef6bae249b.png)

**Comment by zstadler** [comment]
Rendering proposal:
- In zoom level 16, only the members of site relations will be shown as icons, without individual text.
- In lower zoom levels, one icon will be shown for the site. The icon shape, min-zoom and text settings will be based on the relation's tags.

This proposal allows the creation of "natural=cave_entrance" site relations in Beit Guvrin.

**Comment by valleyofdawn** [comment]
Is there a way in the rule set to tag individual points based on their association with a relation?

**Comment by zstadler** [comment]
Either adding something like `... AND NOT relation[type=site].node` will work or I'll need to use maperipy to add special tags for members of site relations.

**Comment by zstadler** [comment]
[This Overpass-Turbo query](http://overpass-turbo.eu/s/rvC) shows all clusters of archaeological sites in Israel where multiple sites exist within 500 meters of each other.
![image](https://user-images.githubusercontent.com/1304610/30129027-41853c60-934d-11e7-9ba2-030705105d06.png)

**Comment by valleyofdawn** [comment]
I can define the relations and @zstadler could try out the relevant rules.

**Comment by valleyofdawn** [comment]
Can we solve it in the vector maps by prioritizing polygon-type archaeological sites over point ones and relying on the uncluttering feature?

**Comment by zstadler** [comment]
The repository is not actively maintained after the transition to vector maps.
