### ISSUE TITLE
Improve visibility of unmarked trails

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#163]
Following [this Facebook post](https://www.facebook.com/groups/994960670559126/permalink/1453527951369060/)

- Use black or darker grey for unmarked tracks and paths. 
- Reduce their line width in order to differentiate from marked trails.

It is possible that the difference between bridges of unmarked trails and black trails will not be clear. For example, [two bridges over Nahal Alexander](http://israelhiking.osm.org.il/#!/16/32.3721/34.9117): one bridge is for a marked trail and the other isn't.

**Comment by zstadler** [comment]
The above changes do not produce enough visibility over dark backgrounds.

Need to explore adding a light background color between the double lines and around single lines.

**Comment by ylivny** [comment]
Wanted to open an issue about the need to have a better distinction between unmarked trails and black trails. Decided to add a comment on this issue instead.

A point that shows the problem is [the path that does south from Har Hashabi](https://israelhiking.osm.org.il/#!/17/32.8387/35.2879)

**Comment by HarelM** [comment]
Surprised me a bit until I remembered this issue, but it looks nice :-)
Probably a full map render is in order now though.

**Comment by ylivny** [comment]
Interesting solution!

I think that you might get complaints about selecting a color that is too close to red (I am pretty sure that people that suffer from color blindness will not be able to distinct between the red an unmarked trails)

**Comment by zstadler** [comment]
This color was tested and tuned for contract with red and black trails, with map background, height contours, and with different satellite imagery backgrounds.

**Comment by HarelM** [comment]
I might be just me, but I think the color of the unmarked trails is a bit overwhelming - it might be also that I'm used to the old color scheme too, not sure, probably more users should comment on this.
The following is a rural area which has a lot of unmarked roads:
http://israelhiking.osm.org.il/#!/14/32.6965/35.2429
I'm not sure I have a good solution for this though.
Maybe consider toning down the color or the intensity for zoom 14 (in 13 they do not appear as much as I can see and I think it's OK for 15 and 16)?
You mentioned something about testing how it looks on satellite imagery - maybe this needs a different rules for overlay tiles?
![unmarked_trails](https://user-images.githubusercontent.com/3269297/31903151-f3d0eebc-b82f-11e7-8aa5-d3d445dba09d.jpg)

The following also used to be a bad area in terms of unmarked trails (even before the change):
https://israelhiking.osm.org.il/#!/14/32.5896/35.1423

**Comment by HarelM** [comment]
Very nice solution! Kudos!

**Comment by zstadler** [comment]
In zoom 14 paths are still too strong and track are too faint.

![image](https://user-images.githubusercontent.com/1304610/32141509-1c55d960-bc8b-11e7-87f4-ec1c6b85074a.png)

_Note:_
This oversight was a result of looking at Maperitive map preview while the tile generation uses `subpixel=2`. To avoid this difference, and other differences, such as label collision detection:
* Select a zoom level and pan to an appropriate map position in Maperitive
* `set-print-bounds-view`
* `export-bitmap  subpixel=2 file=\Temp\zoom14.png zoom=14`
* Open the exported bitmap in a browser tab, the site's map in another tag, and switch between the tabs to compare while panning the site map to match the exported bitmap positon.
