### ISSUE TITLE
 topography contour lines intersection 

### ISSUE THREAD

**Issue by Orrgvili** [IsraelHikingMap/Map#164]
there is intersection in the contour especially in
[http://israelhiking.osm.org.il/#!/16/31.3090/34.9498](http://israelhiking.osm.org.il/#!/16/31.3090/34.9498)

**Comment by zstadler** [comment]
![image](https://user-images.githubusercontent.com/1304610/30312477-723acc4a-97a2-11e7-85c2-db70a317ed38.png)

**Comment by zstadler** [comment]
Unfortunately, there isn't much we can do in Maperitive.
I've contacted the DEM provider to see if there is something it can do.

**Comment by Orrgvili** [comment]
do you have the contour ? 
i can test to see if there is something i can do

**Comment by zstadler** [comment]
Feel free to look at the [DEM data](../tree/master/Cache/Rasters/ASTER)

**Comment by zstadler** [comment]
The issue is a result of the contour generation algorithm in Maperitive. 
For example, in purple below is an overlay of the contours created by gdal using the same DEM:

<img width="462" alt="2017-09-17 09_27_23-gdal_contours" src="https://user-images.githubusercontent.com/1304610/30518605-6d34fcce-9b8b-11e7-9338-9fa197959afd.png">

**Comment by Orrgvili** [comment]
manipulate the data with other software and import it  isn't
 option ?

**Comment by zstadler** [comment]
I'm exploring this option.

**Comment by zstadler** [comment]
I have created a flow where contours in GeoJSON format are created by `gdal_contours` and a perl program translates the GeoJSON to OSM format.

Remaining tasks:
- Find a way to print contours labels, given the lack of support for repeated labels on OSM ways. (See #115 for details)
- Check the feasibility of the solution given the significant increase in memory requirements.

**Comment by zstadler** [comment]
Using an external source for the contour lines is too slow and memory-demanding for Maperitive.

As I see it, only replacing the rendering software with a different technology can resolve this issue.

**Comment by zstadler** [comment]
I'm exploring another approach:

- Use an external renderer to create transparent contour tiles.
- Add the tiles to Maperitive as a custom or offline map source with `draw_in_background = False`.
- Override the default painting cycle for map overlay (900) using a custom workflow, based on Maperitive's `Samples/Python/CustomWorkflow.py`.

**Comment by zstadler** [comment]
The existing map and overlayed with the new contours

<img width="45%" alt="2018-03-02 10_36_12-israel hiking map" src="https://user-images.githubusercontent.com/1304610/36890255-e660c55e-1e05-11e8-8565-4e10c9fa827e.png"> <img width="45%" alt="2018-03-02 10_35_43-israel hiking map" src="https://user-images.githubusercontent.com/1304610/36890260-ebee70b6-1e05-11e8-841c-c6f50c73eceb.png">

**Comment by Orrgvili** [comment]
looks great

**Comment by zstadler** [comment]
Contours are missing from the English maps
