### ISSUE TITLE
Feature request: lighter trails overlay for the MTB map

### ISSUE THREAD

**Issue by mk4th** [IsraelHikingMap/Map#165]
The current overlay includes roads, stronger elevation lines, and more data than just colored trails.
For use during ride I’d like to have just the colored trails as a layer on my MTB map, as it helps navigation, and allows group navigator to free the rest of the group for free pace ride.

**Comment by valleyofdawn** [comment]
It is a question of server space and rendering time.
For use over sat images, the current overlay is good.
For use over other maps, your suggestion makes sense.

**Comment by zstadler** [comment]
@mk4th,
With the existing computing resources, we are unable to take your suggestion.
