### ISSUE TITLE
Font visibility problem in urban areas  

### ISSUE THREAD

**Issue by Orrgvili** [IsraelHikingMap/Map#166]
![image](https://user-images.githubusercontent.com/10514419/30413701-4944f0fe-9928-11e7-8e19-204d64ba1c7f.png)

there is some blurring with the streets name fonts 
and placement problems on road with more then one lane

**Comment by zstadler** [comment]
Given the tile resolution, text bluring can only be reduced by increasing the font size. This could increase hiding of features, as already exists now:
![image](https://user-images.githubusercontent.com/1304610/30646878-fba81f7e-9e22-11e7-98ca-57f890813b20.png)
Increasing the font size could also further prevent the printing of long street names on short street.

I have though long and hard about duplicate names in divided streets. Unfortunately, the infrastructure does not have label collision detection. We were able to minimize such duplication in inter-city road shields. That solution assumes that every inter-city one-way road has a counter-part: a one-way road in the opposite direction. Unfortunately, this cannot be assumed for urban one-way streets.

If you have a proposal, I'd be happy to discuss it.

**Comment by Orrgvili** [comment]
im trying to learn the limitation of the system first

**Comment by zstadler** [comment]
Let's leave this issue in low priority and re-visit it in up-to 6 months.

**Comment by zstadler** [comment]
Addressed as part of #93.
