### ISSUE TITLE
Roads & Tracks obscure POIs & names (of residential area)

### ISSUE THREAD

**Issue by YGMZ** [IsraelHikingMap/Map#169]
(1) see picnic site on "Derech HaPsalim" 4338239529
(2) see מושב תרום 82628888

**Comment by zstadler** [comment]
Generally, text is printed above icons, icons above roads, and roads above areas.

I didn't see any example of a road obscuring a name or a POI icon.

![image](https://user-images.githubusercontent.com/1304610/30646154-b18b9f80-9e20-11e7-87b2-7e14836e7a9b.png)

The above [picnic site on "Derech HaPsalim"](https://israelhiking.osm.org.il/#!/18/31.7751/34.9838) is a good example where the picnic site icon hides part of the road, but is partially hidden by the name of the road.

Can you explain what would you like to change?

P.S., It would be great if in future reports you could add links to map locations and screenshots where applicable. Thanks!

**Comment by YGMZ** [comment]
(1) see the following which looks OK now but few hours ago the track was obscuring the picnic site
        https://drive.google.com/file/d/0BwKVGChbqrLtWVBCZFJuMEdteGs/view?usp=sharing
(2) see the following example which is OK now but few hours ago the roads were obscuring the name תרום.     https://drive.google.com/file/d/0BwKVGChbqrLteTdEcVFMN0tHbGc/view?usp=sharing
Seems to me something inconsistent...

**Comment by YGMZ** [comment]
reason found - MTBM and MTB overlay were on - to be closed
