### ISSUE TITLE
Neither landuse:farm nor landuse:farmland rendered

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#17]
Intentional or glitch?

**Comment by zstadler** [comment]
We also had our doubts. Yet, whenever we tried adding them, they were either unnoticed or over-dominating the map. There are just so many of them.

If you have a specific suggestion, I'd be happy to try it.

By the way landuse=farm is considered n inappropriate tag. See the (OSM wiki page)[http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dfarm]
