### ISSUE TITLE
Update MOBAC tile source definition files to use https 

### ISSUE THREAD

**Issue by goose2019** [IsraelHikingMap/Map#170]
Hi
I followed the manual for creating map for Galileo,
the Mobile Atlas creator does not show the tiles at all, none of the zoom levels is showing.
can you check to see if it works
or maybe post link to download maps for galileo.
Thanks.
Goose

**Comment by zstadler** [comment]
Lately, our server automatically re-directs all connections to a secure connection (https). Apparently, Mobile Atlas Creator does not handle such re-directs.

The tile source definition files should be updated to use https and avoid the automatic redirection.

**Comment by zstadler** [comment]
@goose2019,
Please try the updated map source definition files and close this issue if it it is resolved.

**Comment by goose2019** [comment]
Hi 
Thank you for replying ,
Can you please direct me to a correct xml file,
I've been digging the net for days and cannot find a solution.  
thanks

Thanks
goose

נשלח מה- שלי

‫ב-27 בספט׳ 2017, בשעה 10:51, ‏‏zstadler ‏<notifications@github.com> כתב/ה:‬

**Comment by HarelM** [comment]
The updated file can now be found in this folder:
https://github.com/IsraelHikingMap/Map/tree/master/Mobile%20Atlas%20Creator/mapsources
Here's one of them:
https://github.com/IsraelHikingMap/Map/blob/master/Mobile%20Atlas%20Creator/mapsources/Israel%20Hiking%20Online.xml

**Comment by goose2019** [comment]
First I really want to thank you all,
As it seems the problem was the Java version on my computer not the xml ..
I had tried https before- wasn't sure this was the correct path. 

Thank you,
Wonderful work you do- keep it on. 

Thanks
 
goose
נשלח מה- שלי

‫ב-27 בספט׳ 2017, בשעה 11:58, ‏‏Harel M ‏<notifications@github.com> כתב/ה:‬

**Comment by HarelM** [comment]
No problem! Can we close this issue then?

**Comment by goose2019** [comment]
Sure. 


Thanks
 Goose. 



‫ב-27 בספט׳ 2017, בשעה 12:46, ‏‏Harel M ‏<notifications@github.com> כתב/ה:‬
