### ISSUE TITLE
Correct rendering of shared foot and bike paths

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#174]
## Context - ההקשר

Some highways intended for use by foot and bike are rendered as bike paths.

## Expected Behavior - ההתנהגות הצפויה

According to the legend, general paths that can be used by foot and bike should be rendered differently than foot-only and bike-only paths:
![image](https://user-images.githubusercontent.com/1304610/31055831-a1c00686-a6d1-11e7-84ff-9d4cb619b08b.png)

## Actual Behavior - ההתנהגות בפועל

Some shared paths are rendered as bike paths. For example
![image](https://user-images.githubusercontent.com/1304610/31055862-40e18fd2-a6d2-11e7-931b-9a047fa24ad3.png)
at Tel Aviv [Yehushua Gardens](https://israelhiking.osm.org.il/#!/16/32.1012/34.8127)

## Possible Fix - תיקון מוצע

This is caused by highways tagged as bicycle paths with access to pedestrians, such as [way 391604077](https://www.openstreetmap.org/way/391604077)

## Impact - השפעה

The Hiking map is inconsistent with its legend and shows paths available to pedestrians as bike-only paths.

**Comment by HarelM** [comment]
No sure the possible fix describe what is the proposed solution...?

**Comment by zstadler** [comment]
Add handling of `highway=path foot=no`

**Comment by zstadler** [comment]
Update the legend
