### ISSUE TITLE
Square pool rendering עין אלבעידה

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#175]
## Context - ההקשר
Square pool rendering

## Expected Behavior - ההתנהגות הצפויה
pond should be rendered like other springs?

## Actual Behavior - ההתנהגות בפועל
it is being rendered like a waterway.

## Proposed Cause or Fix - סיבה או תיקון מוצעים
Render icon for water=pond area?

## Steps to Reproduce - הוראות לשיחזור הבעיה
See here:
https://israelhiking.osm.org.il/#!/16/32.7411/35.4554
Probably issue with bad mapping as well
עין אלבעידה.

**Comment by zstadler** [comment]
Mapping such a small pond as an area is probably a wrong decision. `water=pond` nodes are rendered just like springs.

There are many pond areas that render well on the map, such as [אגם ירוחם](https://israelhiking.osm.org.il/#!/15/30.9882/34.8943)

Map editors should fix this and similar small area ponds.

**Comment by HarelM** [comment]
How do you suggest to fix this? removing the pool area and change it to a point?
I don't mind closing this as bad mapping, I'm just not sure what is the right course of action...?

**Comment by zstadler** [comment]
> How do you suggest to fix this? removing the pool area and change it to a point?

Exactly.

> I don't mind closing this as bad mapping, I'm just not sure what is the right course of action...?

What would you suggest if the mapper had created a much smaller area, say 20 x 20 cm?

**Comment by HarelM** [comment]
I honestly don't know - I can understand why one would want to map what's out there but the accuracy of the map can probably never get to present it right.
I'm guessing that the solution is that when we'll be able to properly present it on a map we'll make the effort of fixing the mapping...

**Comment by zstadler** [comment]
As the person that created this little pond, I say again
> Mapping such a small pond as an area is probably a wrong decision.

:-)

**Comment by SafwatHalaby** [comment]
I agree that tiny areas shouldn't be mapped. Well, unless we're talking about a place where someone has taken extremely precise measurements and everything is a precisely mapped area. (You'd probably only see this accuracy level in indoor mapping schemes)

**Comment by SafwatHalaby** [comment]
I see you've changed this to a node. But JOSM warns:

```
WARNING: natural=water on a node. Should be drawn as an area.
```

**Comment by HarelM** [comment]
Feel free to update it - it was a bit too late for me to update that location, probably needs to be man_made or something.
This is how the place looks, I'll upload the image once we decide how it should be mapped.
https://photos.app.goo.gl/0SrVCuzPGgqwks472

**Comment by zstadler** [comment]
It could be tagged as `natural=spring` for the spring that feeds it (in winter), as shown in the photo.

**Comment by HarelM** [comment]
I don't think there's nothing here to do which is related to the map rendering.
