### ISSUE TITLE
Make latest OSM file of Israel publicly available 

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#179]
## Context - ההקשר
As part of looking into the following issue:
https://github.com/IsraelHikingMap/Site/issues/442
I have realized that OSM file is being sent when databases are updated while I need another file (wikipedia dump sql file).
Which led me to think that instead of sending this file for the update process the update process should download it, along with other files it needs (such as wiki db file).

## Expected Behavior - ההתנהגות הצפויה
Latest OSM file of Israel should be available for download much like other files we make publicly available, history can also be saved if needed, but this is more of a "nice to have".
The following is the wiki example:
https://dumps.wikimedia.org/hewiki/latest/
and the site will always download `hewiki-latest-geo_tags.sql.gz` in order to update the wiki POIs.

## Actual Behavior - ההתנהגות בפועל
This file is being sent over the local network and can't be used by other OSM clients.
The latest OSM pbf file is not available, only a daily one that can be downloaded from geofabrik.

## Impact - השפעה
Download bandwidth, although this file is not large and probably the site will be its main downloader but will use local network so I doubt this will have any impact.

**Comment by HarelM** [comment]
To summarize today phone call:
1. There's currently no need to create a file per minute - we agreed half an hour is good enough.
2. The files will be created and stored in a constant location on the server.
3. [Optional] I will test to see if there's a problem to make a large file publicly available - although now that I think about it, we might have the same problem for the offline maps file which are even larger...

**Comment by zstadler** [comment]
There could be a synchronization issue if the OSM file is updated while it is being read.
Therefore, the reader should discard corrupt readrs and restart the process.
To reduce the risk of repeated corruption, the update rate of the OSM file should be reduced. 

Alternatively, the same schaduled task would update the OSM file and then invoke the DB update. 

AFAIK, there was no request for publishing the Israel and Palestine OSM file more than once a day. Even when such a request arrives, it should be considered versus the risks of providing corrupt files.

**Comment by HarelM** [comment]
To clarify things that may not have been clear enough:
I was under the impression both the map creation process and the database updates can use the same location to fetch the relevant OSM file - a file that is up to date at the fetching time.
If this is not the case, and every process needs to manage different versions of the OSM file then please elaborate on the steps to create an updated file so I can replicate the process to the site repository.

**Comment by zstadler** [comment]
It seems that we agree that there is no need for publishing the OSM extract, at least not now.
I would not like to link the map updates with the DB updates. The primary reason is that the time between map updates is unpredictable, and may take hours and even days.

If you agree, please close this issue and open an issue for the site repository. I'll be happy to provide a new version of [UpdateDB.bat](https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/UpdateDB.bat) which will incrementally and independently update an OSM file for the DB updates.

**Comment by HarelM** [comment]
Agree.
The site is using a folder called site-cache.
