### ISSUE TITLE
Labels overlap

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#18]
Prevent labels from overlapping
Very apparent in lower zooms.

**Comment by zstadler** [comment]
* Which labels are you referring to?
* Please give links to a few examples.

Generally, Maperitive does not have control over label overlaps. All we can control is showing or hiding of certain label types at each zoom level. There is a fine balance between showing too many labels at densely mapped areas and not showing enough labels at sparsely mapped areas
