### ISSUE TITLE
Filter irrelevant OSM data and tags

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#181]
OSM data includes many elements and tags that are irrelevant to the map, such as ~100k nodes of `addr:housenumber` and ~30k nodes of `highway=bus stops` nodes.

While usually they do not pose an issue, from time to time mass updates on irrelevant data cause unnecessary delay in the incremental update process.

To overcome this, `osmfilter` can be used to
* Keep only relevant entities
* Keep only relevant tags for them

Moreover, the filter definition could be created automatically from the rule files.

**Comment by SafwatHalaby** [comment]
It's worth noting that SafwatHalaby_bot probably causes many of those mass unnecessary updates, when updating bus stops or names.

**Comment by zstadler** [comment]
This would probably require automatic creation of the filter definitions fron the rule files.
Otherwise, we risk filtering out tags that the rule files would use in the future.

**Comment by zstadler** [comment]
Closing this issue as the ROI isn't high enough.
