### ISSUE TITLE
Bicycle route are rendered as path.

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#184]
## Context - ההקשר
IHM Map

## Expected Behavior - ההתנהגות הצפויה
Bicycle routes should not look like path.
Should be rendered as ._._

## Actual Behavior - ההתנהגות בפועל
Rendered as - - -

## Steps to Reproduce - הוראות לשיחזור הבעיה

1. 
2. 
3. 
4. 

## Your Environment - סביבת העבודה שלך

* Operating System and version - מערכת ההפעלה וגרסתה:    

* Web Browser and version - דפדפן וגרסתו:

**Comment by zstadler** [comment]
See https://github.com/IsraelHikingMap/Map/issues/174
