### ISSUE TITLE
Inconsistent highways rendering in zoom 12

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#186]
## Context - ההקשר
After reviewing a thumbnail created by the server I saw that some highways get broken at zoom 12

## Expected Behavior - ההתנהגות הצפויה
highways should not break.

## Actual Behavior - ההתנהגות בפועל
highways break or not rendered.

## Proposed Cause or Fix - סיבה או תיקון מוצעים
Make sure zoom 12 rendering is consistent for all relevant highway types

## Steps to Reproduce - הוראות לשיחזור הבעיה
1. Look at: https://israelhiking.osm.org.il/#!/12/31.3800/34.4943
2. Now zoom-in to zoom 13 and look at the red track

## Impact - השפעה
Very small, probably most users don't even see it

Zoom 12:
![image](https://user-images.githubusercontent.com/3269297/33746369-6d438a58-dbc5-11e7-8036-4540d218b832.png)

Zoom 13:
![image](https://user-images.githubusercontent.com/3269297/33746391-92e495cc-dbc5-11e7-88ef-837a909d8709.png)

**Comment by zstadler** [comment]
The missing segment is [way 204727615](https://www.openstreetmap.org/way/204727615).
The rendering error is probably a result of its `highway=unclassified` tag.
