### ISSUE TITLE
Galileo Offline maps

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#189]
Copy from https://github.com/IsraelHikingMap/Site/issues/586 opened by @gillss
## Feature
SqliteDB for Galileo Offline maps

## What I expect to happen
Your site has great support for Android users, but we IOS people feel neglected.
Can you please add  SQLiteDB file for GALILEO in the download area?
MOBAC and SASPLANET get a lot of errors trying to download tiles (especially on zoom 16)  

It would be especially nice, if we could be able to download a file you built for us
I believe preparing such a file will reduce the need for massive downloads from the site.

Thank you in advance (for making the IOS people more happy)
Gill

**Comment by zstadler** [comment]
Thanks @gillss for your request.

Providing offline maps is driven by the size of the user base and the technical feasibility. The latest [user poll](https://www.facebook.com/groups/994960670559126/permalink/1440516022670253) shows 3 Galileo users, which are about 1% of the responses.

The currently available offline maps are created in one format which provides offline maps to 90% of the users of applications that accept offline maps. If #178 is implemented, this coverage will reach 96%. Users of less popular apps that need offline maps are requested to prepare them by themselves.

**Comment by zstadler** [comment]
Our server has a pretty good network bandwidth for supporting tile downloads by NMOBAC. Errors in MOBAC's download process are probably on the user end. Please reset your internet modem/router prior to running MOBAC, especially if you are using HOT cable infrastructure.

 You may also try to reduce the number of parallel network connection or set a limit to the download bandwidth in the "network" settings tab:

![image](https://user-images.githubusercontent.com/1304610/34467077-00876306-eef0-11e7-9d42-e3efbfe06cb2.png)

Using "Tile store download only" as the atlas format a few times, until there are no download errors, may also help:

![image](https://user-images.githubusercontent.com/1304610/34467126-ffa2fabc-eef0-11e7-80dc-a51ec9b44d64.png)

**Comment by HarelM** [comment]
Also it's worth trying to ask galileo to support the existing format (oruxmaps).

**Comment by gillss** [comment]
thank you @zstadler for your response.

I've tried all your tips before. the blame is in the MOBAC engine  and not in the setting configuration.
there is a "retry" variable that can't be configured in the MOBAC setting.
This variable causes the loss of multiple packets.
Which leads to a lack tiles.

I manage to mirror your wonderful tiles repository to my PC. (with WGET command)
and then with MOBAC (localy) to make the sqliteDB that we need for Galileo app.
the file contains all your tiles and ready to load into the Iphone app.

if you want ? I can transfer it to you , and you will be able to publish it in your web site.
Perhaps then we will discover that Galileo users are more then your site statistics is showing now.

best regards

gill

**Comment by zstadler** [comment]
Please note that the site does not hold all possible tiles for the rectangular bounding box of Israel. Instead, it tries to minimize the number of generated tiles within a polygon. The shape of this polygon is roughly captured by the MOBAC profiles described in the instructions. However, it is not perfect. Even when these profiles are used, you should expect a few thousand download errors. As far as I've seen the download errors in MOBAC's log file, they were all targeting non-existent tiles.

As far as I understand the issue at hand, I see no reason to modify the existing instructions for preparing offline maps.

P.S., I assume you used the wget command parameters [recommended for tile mirroring](https://github.com/IsraelHikingMap/Map/blob/master/README.md#tile-mirroring)

**Comment by gillss** [comment]
Site managers and all those involved in the project.
It seems that the Messages thet I wrote til now was misunderstood.
Your site is wonderful, and your site gives us mapping solutions that wasn't on the Internet before it.
Your server is fast enough.
And the user interface with all possible extras is simple the best we can ask (and every thing is free !!!)
There is no need to change the site's download instructions.
And I belive there is nothing to change at all.

All I wanted was to save us (iPhone users) the tiles download time from your website.
By creating one SqliteDB file like the DB file you provide to Oruxmaps users.

I think this is the right time to close this isue
meny thanks for your time, for your website and for your wonderful mapping work.

gill

**Comment by HarelM** [comment]
@gillss When we started with this project we used a google drive to store the offline map.
I think you can start with creating an online map for Galileo and store it there, and add a post on facebook with the relevant link, this way other iPhone users can use it, and if we see a large demand we can rethink whether to create it as part of our offline map creation scripts or not.

**Comment by zstadler** [comment]
In addition, offline maps are available for iOS with the Off-road app.
If #178 is implemented, the offline maps will also be available on iOS with Two-nav, including its free version.

**Comment by zstadler** [comment]
This issue can be re-opened if the number of Galileo users or the available server resources increase significantly.
