### ISSUE TITLE
Site and Map ITM coordinates do not match

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#196]
## Context - ההקשר
A user reported on Facebook that ITM coordinates from site search and what can be seen on the map are not aligned.

## Expected Behavior - ההתנהגות הצפויה
Search results of ITM coordinates and map ITM lines should be aligned.

## Actual Behavior - ההתנהגות בפועל
They seem to be a bit off (~3 meters apart)
See here:
https://israelhiking.osm.org.il/#!/?s=dUrrL26Kk1

## Proposed Cause or Fix - סיבה או תיקון מוצעים
The ITM grid was created with a code that was later translated to C# and used by the site but then abandoned due to migration to proj4net.
I think the best solution here will be to regenerate the ITM grid using the new code assuming it is more accurate.

## Steps to Reproduce - הוראות לשיחזור הבעיה
1. Go to site
2. Search for ITM coordinates
3. Draw a line between them
4. Compare lines

## Impact - השפעה
Not sure, credibility?

## Your Environment - סביבת העבודה שלך
Any

**Comment by zstadler** [comment]
I've used QGIS with the official ITM grid definition to evaluate the accuracy of the map grid and the server-side coordinate transformation at ITM location 176000/546000:

<img width="625" alt="2018-01-30 09_42_41-clipboard" src="https://user-images.githubusercontent.com/1304610/35554095-2b1a78d2-05a3-11e8-91f5-8dfb7a63fb83.png">

The map is approx 10 meters away from the server and the server is 0.7 meter from the QGIS location.

The source of difference between QGIS and the server is unclear. Perhaps it is the accuracy of the origin point location.

**Comment by zstadler** [comment]
It would be best if the same .NET package can be used by Maperitive for the coordinate transformation.
I hope it is possible to dynamically load it from Maperipy code.

**Comment by zstadler** [comment]
As a fallback, `ogr2ogr` can also be used for the coordinate transformation.

```
C:\Temp>type grid_ITM.csv & del grid_WGS84.csv
X,Y,id,east,north,grid
150000,500000,1,150,500,ITM
150000,510000,2,150,510,ITM

C:\Temp>ogr2ogr -f CSV -lco GEOMETRY=AS_XY -oo KEEP_GEOM_COLUMNS=NO -oo X_POSSIBLE_NAMES=X -oo Y_POSSIBLE_NAMES=Y -s_srs "+proj=tmerc +lat_0=31.7
3439361111111 +lon_0=35.20451694444445 +k=1.0000067 +x_0=219529.584 +y_0=626907.39 +ellps=GRS80 +towgs84=-24.0024,-17.1032,-17.8444,-0.33077,-1.8
5269,1.66969,5.4248 +units=m +no_defs" -t_srs "+proj=longlat +datum=WGS84 +no_defs" grid_WGS84.csv grid_ITM.csv

C:\Temp>type grid_WGS84.csv
X,Y,id,east,north,grid
34.4802790054141,30.5881245854997,1,150,500,ITM
34.4796070266604,30.6783184897869,2,150,510,ITM
```
