### ISSUE TITLE
Reinstate style of contours in IMBM

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#201]
According to me and several users the new design is too intrusive.
The original rules were:
		// contours
		contour major : contour[@isMulti(elevation, 100) AND NOT elevation=0 ]
		contour medium : contour[@isMulti(elevation, 50) AND NOT @isMulti(elevation, 100)]
		contour minor : contour[@isMulti(elevation, 10) AND NOT @isMulti(elevation, 50)]
		
			target: contour*
		define
			line-color : #841
			line-opacity : 0.75
			curved : false
			painting-cycle : 404
		if : *major
			define
				map.rendering.contour.label : false
				min-zoom : 12
				line-width : 12:0.3;13:0.3;14:1;15:1.5

			draw : contour
			define
				map.rendering.contour.label : true
				min-zoom : 13
				text-color : #320
				text-opacity : 0.8
				text-halo-width : 50%
				text-halo-opacity : 0.75
				text-halo-color : #fff9e6
				font-size : 9
				font-style : italic
				font-weight : normal				
			draw : contour			
		elseif : *medium
			define
				map.rendering.contour.label : false
				min-zoom : 13
				line-opacity : 0.85
				line-width : 13:0.3;15:1
			draw : contour
			define
				map.rendering.contour.label : true
				min-zoom : 14
				text-color : #320
				text-opacity : 0.8
				text-halo-width : 50%
				text-halo-opacity : 0.75
				text-halo-color : #fff9e6	
			draw : contour
		elseif : *minor
			define
				map.rendering.contour.label : false
				min-zoom : 14
				line-opacity : 0.7
				line-width : 14:0.33;15:1
			draw : contour

How can I help implement this?

**Comment by zstadler** [comment]
@valleyofdawn,
It this still a priority?
If not, I would like to close this issue.
