### ISSUE TITLE
 rendering single map from .osm file

### ISSUE THREAD

**Issue by ronitslyper** [IsraelHikingMap/Map#203]
Hi! Can someone who knows the python scripts help me out? I'm looking to render maps for an Israel hiking book, in the style of the default online Israel Hiking Map (the ruleset looks awesome).

The workflow I want:
1) Manually export intended region from openstreetmap.org to an osm file.
2) Apply Israel hiking map ruleset using Maperitive
3) Export to png or preferably svg

When I apply Rules/IsraelHiking.mrules to Binyamina in the Maperitive gui, I get this:
![screen shot 2018-04-01 at 1 23 56 pm](https://user-images.githubusercontent.com/7136941/38172196-5e44ac40-35b0-11e8-940b-bea8257e376c.png)

...obviously the necessary scripts not being applied.

What's the right way to go about this (creating a script that takes an .osm and returns a rendered map)?

Thanks!

Bonus: Also want to switch streetnames to English :)

**Comment by HarelM** [comment]
Did you solve the issue? Can you elaborate on your requirements?
Please note that the code in this repository is for non commercial use only.
If this is for commercial needs please contact us...

**Comment by ronitslyper** [comment]
Thanks for writing! I realized I was approaching the problem the wrong way. Better to render the tiles and stitch together what I needed.

Whoops, didn't realize was non-commercial, my bad for not checking the license (was focused on underlying map data). Decided to go with a different ruleset in the meantime, so no worries. But will keep israelhikingmap in mind for next noncommercial project :).

**Comment by zstadler** [comment]
I'm glad you found a solution.

If you are planning to use Maperitive with the different ruleset, generating tiles and stitching them is an unnecessary step. It is much simpler to use [`export-bitmap`](http://maperitive.net/docs/Commands/ExportBitmap.html) command.

By the way, commercial use of the Israel Hiking and Biking maps and/or code is possible, but we ask to contact us and discuss the terms in advance.

**Comment by ronitslyper** [comment]
Thanks!
