### ISSUE TITLE
Scheduler issues

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#204]
The purpose of this issue is to track issues with the server's scheduler and the creation of offline maps in particular.

**Comment by zstadler** [comment]
Creation of offline maps has stopped. Although the Task Scheduer shows future schedules, when the time comes, the tasks are not eecuted and the "Last Run" date is unchanged.

The task of creating Hebrew maps was exported, deleted, and imported. In the past, such a process has fixed issues with the Task Scheduler.

**Comment by HarelM** [comment]
I think that ES updates are also not running due to this issue (I don't see a ES update every 15 minutes). We'll need see if this is affected/solved too.

**Comment by HarelM** [comment]
Ignore my last comment, not sure if you did anything, but ES updates are running as expected.

**Comment by zstadler** [comment]
Similar export/import was performed for the creation of English offline maps:

![image](https://user-images.githubusercontent.com/1304610/38454400-7aa19740-3a6f-11e8-8e6b-9b91cf004b16.png)

**Comment by zstadler** [comment]
Apparently, it did not solve the issue:
![image](https://user-images.githubusercontent.com/1304610/38608564-68054272-3d84-11e8-9d03-fe7c09120999.png)

The history also does not show any event at the previous "Net Run Time" - 11/04/2018:
![image](https://user-images.githubusercontent.com/1304610/38608994-9874087a-3d85-11e8-9789-a646f3320bba.png)

**Comment by zstadler** [comment]
The server was rebooted to avoid any side-effects of the transition to daylight saving time.

**Comment by zstadler** [comment]
The issue is still unresolved.

![image](https://user-images.githubusercontent.com/1304610/38705071-01608d1e-3eb1-11e8-8387-4a98b2b3664a.png)

**Comment by zstadler** [comment]
That did not help either
![image](https://user-images.githubusercontent.com/1304610/38832509-709e4e06-41cb-11e8-8d02-0264bf5deab1.png)

**Comment by zstadler** [comment]
Changed the security options as follows:
![image](https://user-images.githubusercontent.com/1304610/39410843-05648cfe-4c07-11e8-9ef5-cb6a6c0b792f.png)

**Comment by zstadler** [comment]
The above resolved the issue.

Apparently, the task can be run under a non-Administrator user.
