### ISSUE TITLE
בעית כתוביות במפת הטיולים  בעין תנור 

### ISSUE THREAD

**Issue by Orrgvili** [IsraelHikingMap/Map#205]
כתובית על כתובית  ולא ממש ניתן לקרוא את שם המעיין  אני חושב ששם המעיין חשוב יותר  מזה שהעץ הוא תאנה 

![image](https://user-images.githubusercontent.com/10514419/38458997-eaf627c6-3aac-11e8-926e-aed85a636b5a.png)

**Comment by zstadler** [comment]
Duplicate of #202
