### ISSUE TITLE
add to osm dont work when try to update 

### ISSUE THREAD

**Issue by Orrgvili** [IsraelHikingMap/Map#206]
i upload new recording of updates made to single 
cant update the new parts 
i received the following massage 
לא ניתן לשלוח את המסלול

[SinglMitar_new.gpx.txt](https://github.com/IsraelHikingMap/Map/files/1931292/SinglMitar_new.gpx.txt)

**Comment by HarelM** [comment]
I have moved this issue to the site repository as it doesn't concern the map creation process.
