### ISSUE TITLE
Better distinction between grade2 tracks and unclassified roads

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#208]
Since both grade2 tracks and unclassified roads have solid borders, it is hard to distinguish between them. 

For example:
[<img width="25%" src="https://user-images.githubusercontent.com/1304610/39816684-97ce102a-53a4-11e8-8d72-8f7a924ab198.png">](https://israelhiking.osm.org.il/#!/16/33.0345/35.2356)

Only a keen eye can detect that the blue and the red trails are unclassified roads, with white fill, while the black trail is a grade2 track, with no fill.

## Proposed Fix - תיקון מוצע
Introduce a transparent brown fill for tracks. Special attention need to be given to non-colored grade2 tracks that have brown borders.

**Comment by HarelM** [comment]
Can you do a screenshot of the proposed solution? I'm having a hard time imagining it...

**Comment by zstadler** [comment]
Rough draft:
<img width="25%" src="https://user-images.githubusercontent.com/1304610/39836153-1c359c12-53db-11e8-9b85-639e5d7c7fda.png">
The exact color and opacity are TBD
