### ISSUE TITLE
add option to transparent path

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Map#211]
## Context - ההקשר
בשטח לפעמים מופיעים סימונים שקופים שמסמנים שבילים קצרים לנקודות עניין.
במפת סמ״ש הם לא מופיעים אבל ב־IHM הם מסומנים בצורה לא ברורה.

## Expected Behavior - ההתנהגות הצפויה
צריך להיות סימון מתאים במפה לשבילים שקופים.

## Actual Behavior - ההתנהגות בפועל
השבילים האלה מופיעים במפה בדרך כלל כשבילים לא מסומנים. אם מוסיפים colour=transparent השביל יופיע בסימון שחור.
לעומת זאת את היחס שלו אפשר לסמן osmc:symbol=black:white אבל המפה מתעלמת מזה

## Proposed Cause or Fix - סיבה או תיקון מוצעים
צריך להיות סימון מתאים במפה לשבילים שקופים.

## Steps to Reproduce - הוראות לשיחזור הבעיה
ראו את השביל המוביל לחורבת צפיר
https://israelhiking.osm.org.il/poi/OSM/way_312076317?language=he
הוא אמור להיות שקוף אבל מופיע כלא מסומן.
לעומת זאת השביל לגבעת חרוט מוגדרת colour=transparnt ומופיע כשביל שחור.

**Comment by HarelM** [comment]
לדעתי, סימון שקוף וללא סימון משיג המטרה: השביל נראה על המפה בצורה מספיק בולטת.
לסמן אותו בכל צבע שקיים בסימונים אחרים זו טעות.
אם יש לך רעיון אחר, נשמח לשמוע. סימון שביל שקוף בצורה הנוכחית היה הפתרון שאנחנו מצאנו לבעיה.

**Comment by amiad** [comment]
המפה צריכה לייצג את השטח וצריך להיות הבדל בין שביל שקוף לשביל לא מסומן.
אפשר לסמן אותו באפור בהיר, בקווקווים מתחלפים או בנקודות שחורות במילוי לבן. אני מניח ששתי האפשרויות האחרונות יהיו מסובכות טכנית.

בכל מקרה, צריך למנוע ש־colour=transparent יסומן בשביל שחור. אני מבין שכרגע transparent הוא ערך לא חוקי אבל עדיין זה עלול לגרום לבלבול. למשל בגבעת חרוט.
https://israelhiking.osm.org.il/poi/OSM/node_1100955120?language=he

**Comment by zstadler** [comment]
זו אכן טעות שלא לצייר שביל שלא בצבע הסימון שלו או בחום.

המפה לא יכולה לייצג את כל מה שיש בשטח וגם לא את כל מה שיש במסד הנתונים של 
OSM
זו בחירה של מעצב המפה - מה יוצג, באילו רמות זום ואיך.

יתרה מזאת, השבילים השקופים גם לא מופיעים במפת סימון השבילים של החברה להגנת הטבע שאחראית על יצירת הסימון הזה.

למרות זאת, אשמח לשמוע על צבע שיוכל לייצג שבילים שקופים. אפור הוא לא אופציה כי הגוונים שלו קרובים מדי לשחור או שלא ניתן להבחין בהם על גבי הרקעים השונים של המפה. צורת הקו מייצגת את סוג הדרך ולכן לא מתאימה לייצג את סימון השביל

נ.ב., לדעתי 
colour=transparent
הוא ערך לגיטימי שמייצג בצורה אמיתית וברורה את המצב בשטח.

**Comment by zstadler** [comment]
בהעדר הצעה איך להציג שבילים שקופים על המפה, אני סוגר את הקריאה
