### ISSUE TITLE
ESRI base maps hides overlays

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#214]
## Context - ההקשר

Using custom ESRI base map with overlays

## Expected Behavior - ההתנהגות הצפויה

Map overlays should be visible on top of ESRI base maps

## Actual Behavior - ההתנהגות בפועל

ESRI base maps are covering map overlays

## Steps to Reproduce - הוראות לשיחזור הבעיה

1. Open the https://israelhiking.osm.org.il/share/JoKWORRFxK
2. You may be able to see the overlay downloaded first    
    <img width="419" alt="2018-09-04 10_15_49-israel hiking map" src="https://user-images.githubusercontent.com/1304610/45015826-8ff3c500-b02b-11e8-819a-f7db76a50202.png">
    and then the ESRI base map covers it:
    <img width="419" alt="2018-09-04 10_15_51-israel hiking map" src="https://user-images.githubusercontent.com/1304610/45015843-9a15c380-b02b-11e8-9a23-239d38e28aad.png">

This also happens in private/anonymous mode

## Your Environment - סביבת העבודה שלך

* Operating System and version - מערכת ההפעלה וגרסתה:    Win 10 home
* Web Browser and version - דפדפן וגרסתו: 
  - Firefox 56.0.2 (64-bit)
  - Microsoft Edge 42.17134.1.0
  - Chrome 68.0.3440.106 (Official Build) (64-bit)

**Comment by HarelM** [comment]
Wrong repository?

**Comment by zstadler** [comment]
yes
