### ISSUE TITLE
Passable gates appear as closed gates on MTB & IHM

### ISSUE THREAD

**Issue by YGMZ** [IsraelHikingMap/Map#220]
Gate passable by hikers and bikers are shown as closed gates on MTB & IHM.
Was OK in previous versions, something went wrong on this version
see examples:
gate at:
 31.782101°, 35.131241° (רוחב, אורך)
212523 / 632158 (מז', צ')
גובה 663 מ'
gate at:
31.785548°, 35.130919° (רוחב, אורך)
212493 / 632540 (מז', צ')
גובה 722 מ'

**Comment by valleyofdawn** [comment]
This is a change in the symbology to be published soon. We have began using the same icons for the hiking and biking maps. From now on black is an open gate and red is a closed one. I know it's confusing but it will bear out in the longer run.

**Comment by YGMZ** [comment]
I suggest to show 3 types of gates
1 - open to all
2 - open to hikers or bikers & closed to vehicle
3 - open to none
I would use shape rather then color,
but if color is used then I would use 3 colors the differentiate the 3 types (green, black, red)

**Comment by HarelM** [comment]
See the discussion in #160. It's a long one, search for gates.
There's no real benefit in showing a gate that is open to all.

**Comment by valleyofdawn** [comment]
But we do show open gates. They might be closed some of the time, e.g.
Shabbat, and they serve as a waymark.

**Comment by YGMZ** [comment]
I agree with Guy

**Comment by zstadler** [comment]
I prefer that the difference between an open and a closed gate is in one aspect only. Otherwise the reader could wonder what is a black gate with an inside X or a red gate with a diagonal inside.
