### ISSUE TITLE
אנדרטה אינה מופיעה במפת האפניים

### ISSUE THREAD

**Issue by YGMZ** [IsraelHikingMap/Map#226]
אנדרטה (יד אסא) אינה מופיעה במפת האפניים.
מופיעה תקין במפת הטיולים. 
  אנדרטאות אחרות באזור (באזור מעלה החמישה למשל) נראות תקין.

![memorial](https://user-images.githubusercontent.com/31124242/50544544-6f1a3580-0c01-11e9-9c9e-ffdd857d5f79.jpg)

**Comment by zstadler** [comment]
@valleyofdawn,
Do you plan to address this issue?
If not, please close it.
