### ISSUE TITLE
Campsite name is very small and hard to read

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#227]
## Context - ההקשר
Looking at the map

## Expected Behavior - ההתנהגות הצפויה
To be able to read campsite name

## Actual Behavior - ההתנהגות בפועל
Extremely hard to read campsite name and I don't need glasses...

## Proposed Cause or Fix - סיבה או תיקון מוצעים
Increment text size

## Steps to Reproduce - הוראות לשיחזור הבעיה
Search for חאן השיירות
https://israelhiking.osm.org.il/beta/poi/OSM/node_1095683927?language=he

## Impact - השפעה
?

## Your Environment - סביבת העבודה שלך

* Operating System and version - מערכת ההפעלה וגרסתה:  Windows 10, using 4k screen.  

* Web Browser and version - דפדפן וגרסתו:   Chrome latest.

Here's how it looks, not sure github will keep the original size though:
![image](https://user-images.githubusercontent.com/3269297/51064145-e3dc6f00-1606-11e9-9042-7005285b33cd.png)

**Comment by zstadler** [comment]
What text size would you suggest? Similar to what other entity?

**Comment by zstadler** [comment]
The vertical alignment of the text below the icon was restored in 55e57e947efb0605258ad589fa690c8623b0585d after breaking it in 00e4881747f27b8bbcf96ed819c4249bf2f2bbe4
