### ISSUE TITLE
[Bug] Downloading a trail (.GPX) fails as MacOS Safari browser downloads broken .DMS file instead

### ISSUE THREAD

**Issue by arieltolkachov** [IsraelHikingMap/Map#228]
## Context - ההקשר

יצרתי מסלול אופניים 
https://israelhiking.osm.org.il/share/vwFruCDguF

כשאני מנסה להוריד אותו לקובץ ג׳י פי אקס, דפדפן הספארי פשוט מוריד קובץ שבור עם סיומת די אמ אס
עובד על מאק, עם דפדפן אחר (כרום) זה לא משתחזר. כנראה משהו נקודתי לספארי. 

## Steps to Reproduce - הוראות לשיחזור הבעיה

1. 
2. 
3. 
4. 

## Your Environment - סביבת העבודה שלך

* Operating System and version - מערכת ההפעלה וגרסתה:    

* Web Browser and version - דפדפן וגרסתו:    
MacOS 10.14.3
Safari 12.0.3

**Comment by zstadler** [comment]
Hello @arieltolkachov,

Thank you for your report.

This repository is about the maps shown at the site. The site itself, including the ability to plan trails and download their files is developed in a different repository. 

Please open the issue at
https://github.com/IsraelHikingMap/Site/issues/new

**Comment by HarelM** [comment]
@arieltolkachov the site has been updated tonight with a possible fix to this issue (and a major infrastructure change).
Can you please refresh the site and try it again?
I have tested it locally on a virtual machine and it worked as expected.
In case there's still an issue please use the link provided by @zstadler to open an issue in the site's repository.

**Comment by arieltolkachov** [comment]
Yep. Works like a charm this morning. Thank you for the quick fix. 
On another note (and please do let me know if you want a separate ticket for that), the UI language was changed to English, despite having "Hebrew" chosen. I can only assume this was introduced with this big release you mentioned in your last comment.

Cheers,
Ariel

**Comment by HarelM** [comment]
@arieltolkachov please open a separate issue using the following link:
https://github.com/IsraelHikingMap/Site/issues/new
I have tested it locally with an incognito window and the default seem to be Hebrew so please elaborate what were the steps you did in order to reproduce this issue when you write the ticket.
Thanks again for taking the time and reporting issues you find.
