### ISSUE TITLE
New IHM instance keeps old route

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Map#229]
## Context - ההקשר

Starting a new IHM instance in a new tab by opening the site web page, https://israelhiking.osm.org.il, loads the site with the last viewed route, instead of just the map without any routes.

## Expected Behavior - ההתנהגות הצפויה

Site should load clean, without any route/points loaded.

## Actual Behavior - ההתנהגות בפועל

Site loads with an old route.

## Steps to Reproduce - הוראות לשיחזור הבעיה

1. Load a route
2. (optional) Close window
3. Open a new tab in browser and navigate to https://israelhiking.osm.org.il

## Your Environment - סביבת העבודה שלך

* Operating System and version - מערכת ההפעלה וגרסתה:    
Windows 10

* Web Browser and version - דפדפן וגרסתו:    
Chrome 71.0.3578.98

**Comment by HarelM** [comment]
Thanks for reporting.
This is by design to prevent data loss.
Also this is the wrong repository.
If this answer doesn't suites you, please open an issue in the Site repository.
