### ISSUE TITLE
Can't load shared routes from mobile 

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Map#230]
## Context - ההקשר

Links to shared routes open fine on a PC but fail to load from a mobile device

## Expected Behavior - ההתנהגות הצפויה

Site should load with route

## Actual Behavior - ההתנהגות בפועל

Site doesn't load at all

## Steps to Reproduce - הוראות לשיחזור הבעיה

1.  Share a route with a link
2. Open link on a mobile device

## Your Environment - סביבת העבודה שלך

* Operating System and version - מערכת ההפעלה וגרסתה:    
iPhone and apparently Android devices as well

* Web Browser and version - דפדפן וגרסתו:    
Chrome and Safari.

**Comment by HarelM** [comment]
Thanks for reporting.
Please open this issue in the Site repository and include a link example.
