### ISSUE TITLE
Missing renderd colours for stairways (higway:steps) in marked trails

### ISSUE THREAD

**Issue by krooven** [IsraelHikingMap/Map#232]
Please refer here 
https://israelhiking.osm.org.il/map/17/30.8250/34.7645

color should apply for marked path also when it tag as steps.

**Comment by zstadler** [comment]
Good catch!

Also, a halo is missing for the stairs to show them above dark backgrounds.

![image](https://user-images.githubusercontent.com/1304610/52694555-c0dd0c00-2f72-11e9-829d-bda7493ebcea.png)
