### ISSUE TITLE
A marked path that was updated in OSM a week ago does not appear in IHM

### ISSUE THREAD

**Issue by ylivny** [IsraelHikingMap/Map#234]
## Context - ההקשר
A week ago I made some changes in OSM (username: ylivny) in the area of [תל שוכה](https://israelhiking.osm.org.il/share/f7AVqF8pxH).

Among the changes:
1) change the type of path that crosses the תל from 4x4 to hiking path
2) extend the blue trail to south (see attached images) by adding paths to relation 3562874 (in order to do so I had to split path 671094054 to two)
![ihm](https://user-images.githubusercontent.com/32610763/53284752-15496e00-3761-11e9-8c7b-9ce73753c078.JPG)

While the 1st change is seen in IHM, the 2nd one doesn't.
When I check the path I extended in OSM it is part of relation 3562874 (see attached image)
![ihm osm](https://user-images.githubusercontent.com/32610763/53284754-1e3a3f80-3761-11e9-9b0f-39c83df68e0f.JPG)

When I use Waymarked Trials site to look at the area I see that the blue path is extended (see attached image).
![ihm waymarked trails](https://user-images.githubusercontent.com/32610763/53284759-2c885b80-3761-11e9-9308-4c0ec25ae28b.JPG)

Is there something I am doing wrong?

## Expected Behavior - ההתנהגות הצפויה
The blue path should be extended all the way south till junction with red trail

## Actual Behavior - ההתנהגות בפועל
The blue path is not extended

## Proposed Cause or Fix - סיבה או תיקון מוצעים
Maybe I did not perform the change correctly?

## Steps to Reproduce - הוראות לשיחזור הבעיה
-

## Impact - השפעה
-

## Your Environment - סביבת העבודה שלך
* Operating System and version - מערכת ההפעלה וגרסתה:    
Windows 10

* Web Browser and version - דפדפן וגרסתו:    
Chrome 72.0.3626.119

**Comment by zstadler** [comment]
Hello @ylivny,

Welcome back to OSM and thank you for your edits!

Please review the [Conventions for Hiking and Biking_Trails](https://wiki.openstreetmap.org/wiki/WikiProject_Israel#Conventions_for_Hiking_and_Biking_Trails) on the OSM Israel wiki page, and the section about [Ways Belonging to a Trail](https://wiki.openstreetmap.org/wiki/WikiProject_Israel#Ways_Belonging_to_a_Trail).

Specifically, please add the a `colour=blue` tag to the appropriate ways.

**Comment by ylivny** [comment]
Thanks!
