### ISSUE TITLE
אי אפשר להוסיף תמונה לעין ירקעם

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Map#235]
## Steps to Reproduce - הוראות לשיחזור הבעיה

1. 
2. 
3. 
4. 

## Your Environment - סביבת העבודה שלך

* Operating System and version - מערכת ההפעלה וגרסתה:    

* Web Browser and version - דפדפן וגרסתו:

**Comment by HarelM** [comment]
Closing in favor of (other repository):
https://github.com/IsraelHikingMap/Site/issues/986
