### ISSUE TITLE
red tiles in map 

### ISSUE THREAD

**Issue by Orrgvili** [IsraelHikingMap/Map#236]
פתחתי את המפה באזור ערד   (https://israelhiking.osm.org.il/share/ftWAwMvfhy) וגם באזור מכתש רמון (https://israelhiking.osm.org.il/share/sIkshpCJWr)
ומופיעים לי ארחים אדומים  כמו בקובץ המצורף 
זה רק בזום מסויים ואזורים מסויימים 
![red](https://user-images.githubusercontent.com/10514419/54526381-493e3a80-497f-11e9-96dd-76f88145ae9d.PNG)

**Comment by HarelM** [comment]
This is probably a cache issue.
Please refresh the browser using Shift+F5.
If this works, please close this issue.

**Comment by Orrgvili** [comment]
tried it  even deleted the cache still the same

**Comment by HarelM** [comment]
I don't see this red tile when surfing to your share. Have you tried inconito mode?

**Comment by Orrgvili** [comment]
inconito  its fine 
its something localize to this pc  
ill close it
