### ISSUE TITLE
Block icon

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#24]
http://osm.org.il/IsraelHiking/#/17/32.9025/35.6166?baselayer=Israel_Hiking_Map&markers=&Route_1=
This Icon does not appear in the legend.
I think we should use the positive instead of the negative (or if you find a better icon even better), I thought it was a cable-cart...

**Comment by zstadler** [comment]
I've tried the positive, and it was not clear if it's not a couple of buildings side by side...

Perhaps change it from black to red!?

**Comment by HarelM** [comment]
See if you can render a red file and upload it here. If it will look good we'll adopt it.

**Comment by zstadler** [comment]
@HarelM Here are a few options

1. ![barrier_blocks n da0092 32](https://cloud.githubusercontent.com/assets/1304610/14560156/6fe4786e-0316-11e6-905a-0556413c78c5.png)
2. ![barrier_blocks p da0092 32](https://cloud.githubusercontent.com/assets/1304610/14560171/8367c3e6-0316-11e6-85ca-389281ad20f2.png)
3. 
![barrier_blocks da0092 000000](https://cloud.githubusercontent.com/assets/1304610/14560348/dc8c4fb8-0317-11e6-9b4b-6596e32f0a35.png)
4. 
![barrier_blocks 000000 da0092](https://cloud.githubusercontent.com/assets/1304610/14560456/9cd35118-0318-11e6-8f1a-001a84785d7b.png)
5. 
![barrier_blocks fcff00 000000](https://cloud.githubusercontent.com/assets/1304610/14560946/aa7c0df2-031b-11e6-88be-9a089e7d0453.png)
6. ![barrier_blocks 000000 fcff00](https://cloud.githubusercontent.com/assets/1304610/14560945/aa79b66a-031b-11e6-9456-7b506c35434c.png)

Clearly, other color combinations are also possible.

**Comment by HarelM** [comment]
I think it should not have a background. Just the stones. But I don't like the pink much... Can we find like stones in a pyramid icon?

**Comment by HarelM** [comment]
Maybe something like this?
http://superawesomevectors.com/black-simple-spa-stones-vector-icon/
or one  of the icons in this page?
http://vallecustommasonry.com/

**Comment by zstadler** [comment]
Here are the latest options:

Option | Icon | Screenshot
---------|-----|----------
spa-stones | ![black-simple-spa-stones-vector-icon](https://cloud.githubusercontent.com/assets/1304610/15022568/f695c818-1234-11e6-85e6-d3fc18b57306.png) | <img width="162" alt="2016-05-04 18_54_30-maperitive v2 3 35" src="https://cloud.githubusercontent.com/assets/1304610/15022633/42bbfe88-1235-11e6-8e30-9e156b3c805c.png">
jersey_barrier | ![jersey_barrier](https://cloud.githubusercontent.com/assets/1304610/15022585/0a5b74f6-1235-11e6-9634-09284a18df9e.png) | <img width="96" alt="2016-05-04 20_14_25-maperitive v2 3 35" src="https://cloud.githubusercontent.com/assets/1304610/15022639/4947e03c-1235-11e6-987b-8c53e9e9d298.png">
barrier_blocks | ![barrier_blocks n 32](https://cloud.githubusercontent.com/assets/1304610/15022698/8baec076-1235-11e6-8e79-42d952c0cdc5.png) | <img width="86" alt="2016-05-04 19_03_49-maperitive v2 3 35" src="https://cloud.githubusercontent.com/assets/1304610/15022625/38d8dcba-1235-11e6-8bb5-51b3828fe439.png">

My preference is for the jersey_barrier.

**Comment by zstadler** [comment]
jersey_barrier was used
