### ISSUE TITLE
Avenue names are duplicated

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#240]
Copied from https://github.com/IsraelHikingMap/Site/issues/1056, reported by @Tsurha 

## Bug
שדרה המסומנת בשני קוים במפה אחד לכל כיוון
רואים את שם השדרה פעמיים באופן שגראפית לא נוח - ראה קובץ מצ"ב

![Capture](https://user-images.githubusercontent.com/49042192/63215861-70b75000-c135-11e9-8ecb-23ac3a8821a1.JPG)

## What I expect to happen
שיראו רק בכיוון אחד

**Comment by zstadler** [comment]
לצערנו, לא מצאנו דרך להמנע משמות כפותים בכבישים עירוניים. בכבישים בין עירוניים ברור שיש כבידים חד כיווניים בשני הכיוונים ואנחנו יכולים להחליט אקראית על הסתרת השם של אחד הכיוונים. בשדרות עירוניות אין לנו מידע אם מדובר בכביש חד כיווני בודד או שזהו חלק משדרה.
אם ישלך הצעה כיצד ניתן לזהות שדרות בנפרד מכבישים חד כיווניים, נשמח לראות אם ניתן לשלב את הקריטריון  הזה בקוד יצירת המפות.

**Comment by zstadler** [comment]
No response, closing.

**Comment by Tsurha** [comment]
היי אכן שכחתי לענות.
מציע לרווח את השמות בין צד אחד לצד השני של השדרה. כפי שעושים ב
OSM
ככה הם לא יהיו אחד על השני שגראפית לא יפה
ראה קובץ:

![Capture](https://user-images.githubusercontent.com/49042192/67148274-a3e99d00-f2a6-11e9-9169-d8ed7c1768b1.PNG)

**Comment by zstadler** [comment]
הריווח במפות האלו הוא תוצאה של מנגנון מניעת התנגשויות בין תוויות, שלא קיים בתוכנת יצירת המפות שבשימוש האתר.

**Comment by Tsurha** [comment]
העלית אחלה רעיון. תוסיפו מנגנון של מניעת התנגשויות בין תויות וזה יראה הרבה יותר יפה גם בשדרות עירוניות

**Comment by zstadler** [comment]
לצערי, אין לנו גישה לקוד המקור של התוכנה ובנית מנגנון כזה היא לא אופציה
