### ISSUE TITLE
MTB-IL: Road name not presented for "Primary Road"

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#241]
This bug was copied from https://github.com/IsraelHikingMap/Site/issues/1057, reported by @Tsurha 
## Bug

See capture and highlight:

![Capture](https://user-images.githubusercontent.com/49042192/63215926-5336b600-c136-11e9-9a04-3ac5c4b4cea7.JPG)

## What I expect to happen
That its name will show

This happens only in MTB-IL map, it doesn't happen in IHM map.
This was captured in Raanana.

**Comment by zstadler** [comment]
@valleyofdawn,
Do you plan to address this issue?
If not, please close it.
