### ISSUE TITLE
Missing a wadi on the map

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#242]
## Context - ההקשר
See a wadi on the map

## Expected Behavior - ההתנהגות הצפויה
Wadi should appear

## Actual Behavior - ההתנהגות בפועל
It doesn't

## Proposed Cause or Fix - סיבה או תיקון מוצעים
Present it on the map

## Steps to Reproduce - הוראות לשיחזור הבעיה
1. Go to: https://israelhiking.osm.org.il/poi/OSM/way_546426989?language=he
2. In OSM: https://www.openstreetmap.org/way/546426989

## Impact - השפעה
Low

## Your Environment - סביבת העבודה שלך
Win 10, but I don't think it is related.

* Web Browser and version - דפדפן וגרסתו:
Any

**Comment by zstadler** [comment]
The missing Wadi was restored when the map was rebuild.

Most likely this was a side effect of the change in map data source to geofabrick.de and back to openstreetmap.fr
