### ISSUE TITLE
לא מצליח להעלות נקודה

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Map#244]
היי
אני מנסה להעלות נקודת עניין ציבורית למפה ונתקל בהודעה
אין באפשרותינו לשמור כרגע

win7 32 bit chromeניסיתי כמה פעמים בשעות שונות

**Comment by HarelM** [comment]
תוכל לפרט איזו נקודה בדיוק ומה השלבים שאתה עושה?

**Comment by onzd** [comment]
אני מנסה לעלות נקודה בנחל סלבדורה את נקודהת השיח העצום שם עם תמונה
השלבים הם:לחיצה על נקודת עניין מצד ימין
העלאת תמונה 
ולחיצה על הוי למעלה לאישור
ניסיתי גם להעלות נקודה ללא צילום והיינו הך

**Comment by zstadler** [comment]
@onzd 
אני מקווה שהבעיה נפתרה. אם לא, פתח בבקשה דיווח חדש בנושאים של האתר
https://github.com/IsraelHikingMap/Site/issues/new
הנושאים כאן מתיחסים למפות הטיולים והאופניים המוצגות באתר
