### ISSUE TITLE
מערות הקבורה בחרמש אינן מופיעות המפה

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Map#246]
למרות שהן מופיעות בעריכה
https://www.openstreetmap.org/edit#map=19/32.64181/35.06900

**Comment by HarelM** [comment]
True, here's another example:
https://www.openstreetmap.org/node/3961410967
I'm not sure they are interesting enough in most cases, but it's worth considering adding them.

**Comment by zstadler** [comment]
The Hiking map will be enhanced to show a cave icon for `tomb=rock-cut`.
