### ISSUE TITLE
כמה זמן לוקח עידכון שביל במפה

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Map#247]
הקלטתי ביום שבת 22.2.20
 שביל חדש באזור אבנת העלתי אותו למפה ועדיין לא מופיע
https://israelhiking.osm.org.il/share/v2u67qe81M

**Comment by zstadler** [comment]
העדכונים של המפה נעשים ברציפות. כשמסתיים עיכון מתחיל העדכון שאחריו. זמן העדכון תלוי בהיקף השינויים שנעשו במפה. עדכון של שינויים קטנים אורך כשעתיים.

לעיתים רחוקות אנו מבצעים בניה מחדש של המפה, ללא קשר לשינויים שנעשו בה. הדבר נעשה כאשר אנו משנים את קוד יצירת המפה. בשבוע האחרון התבצעו [שינויים במפת האופניים ובמפת הטיולים](https://github.com/IsraelHikingMap/Map/commits/master) וכרגע מתבצע "עדכון גורף" לשתי המפות בהסתמך על המיפוי נכון לתאריך
2020-02-20T16:23:02Z

עם סיום העדכון הזה, בתוך שעות בודדות, יתחיל עדכון שיכלול את כל השינויים מאז, כולל השביל שמיפית.
מטבע הדברים העדכון הזה יארך זמן רב מהרגיל.

תודה על הסבלנות.

**Comment by onzd** [comment]
תודה רבה
אני תמיד חושש אם עשיתי משהו לא נכון

**Comment by zstadler** [comment]
אתה תמיד יכול לראות את המיפוי באתר של OSM. למשל,
https://www.openstreetmap.org/#map=17/31.67716/35.44474
