### ISSUE TITLE
Cannot edit wrong paths

### ISSUE THREAD

**Issue by yargolan** [IsraelHikingMap/Map#248]
## Context - ההקשר

I'd be happy to fix it myself, only I didn;t manage to do it even when walking through the tutorials.
Sorry.

## Actual Behavior - ההתנהגות בפועל

![image](https://user-images.githubusercontent.com/5415524/77827233-88bc6c80-7125-11ea-87b1-bc7cbd5d9954.png)

## Proposed Cause or Fix - סיבה או תיקון מוצעים

There are 2 mistakes in the map at the screenshot attached.
1. The "brown" path does not actually exits. Needs to be deleted from the map
2. The black "SAMASH" should be a strait line. There are no curves at this point.

![image](https://user-images.githubusercontent.com/5415524/77827290-c620fa00-7125-11ea-8935-e2217d353ca3.png)

## Steps to Reproduce - הוראות לשיחזור הבעיה

1. Just look at the map at the area of "Mitzpe Modiin"
![image](https://user-images.githubusercontent.com/5415524/77827372-43e50580-7126-11ea-830d-43d31e404b08.png)

## Impact - השפעה

It doesn't affect me as I know the place by heart.
For others, which looks for this path and won't be able find it, much bigger issue.

## Your Environment - סביבת העבודה שלך

* Operating System and version - מערכת ההפעלה וגרסתה:    

* Web Browser and version - דפדפן וגרסתו:    
Not relevant.
It is shown at all OSs / browsers

**Comment by zstadler** [comment]
@yargolan It looks like you were able to edit the map. Please note that the walking path was disconnected from the dirt-road

![image](https://user-images.githubusercontent.com/1304610/79940955-d352af80-846b-11ea-9b77-fc9bddedd09c.png)
