### ISSUE TITLE
map disply in the app 

### ISSUE THREAD

**Issue by Orrgvili** [IsraelHikingMap/Map#252]
the map disply in the app 
the labels are under the  fetures and not readable
when using the site in crome its fine on pc and phone 

im using pixel 4a with android 11 

![Screenshot_20210804-193613](https://user-images.githubusercontent.com/10514419/128220666-d795ae75-2b28-4efb-9c1e-b02fd266b006.png)

**Comment by HarelM** [comment]
Probably an issue with the overlays.
Can you hide all the overlays? שכבות שקופות

**Comment by Orrgvili** [comment]
צודק 
לא משמש בהן ומשום מה זה היה פעיל
