### ISSUE TITLE
link to offline maps is dead

### ISSUE THREAD

**Issue by benayat** [IsraelHikingMap/Map#253]
## Context - ההקשר

בקישור הבא: https://israelhiking.osm.org.il/Hebrew/Oruxmaps/IsraelMTB16.zip 
הייתי רגיל להוריד את המפה, עכשיו הקישור לא עובד. 
האם זה כבר לא שמור בענן?
או שאני מפספס משהו?

## Expected Behavior - ההתנהגות הצפויה

הקישור אמורה להוריד את המפה

## Actual Behavior - ההתנהגות בפועל

קישור מת. 

## Steps to Reproduce - הוראות לשיחזור הבעיה

1. 
2. 
3. 
4. 

## Impact - השפעה

חשבתי להשקיע קצת במפה ולעדכן אותה, או סתם להוריד.

## Your Environment - סביבת העבודה שלך

* Operating System and version - מערכת ההפעלה וגרסתה:    

* Web Browser and version - דפדפן וגרסתו:    
chrome - 94.0.4606.61

**Comment by HarelM** [comment]
The link is incorrect, you can find the right file by surfing to https://israelhiking.osm.org.il/Hebrew/
There's a case difference in the address which was changed when we migrated to linux server.
The file is still there.

**Comment by benayat** [comment]
אחלה, תודה!
