### ISSUE TITLE
Place the LastModifiedDate.js file in Tiles folder

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#27]
In order to prevent copying of files from one location to the other the js file should be created in the same directory as the tiles. The site will use that directory the same way it uses the tiles.

**Comment by zstadler** [comment]
There are 3 Tile directories: Tiles, OverlayTiles, and mtbTiles. 
Where would you want the file, or do you want 3 files, one in each directory?

**Comment by HarelM** [comment]
Currently just in Tiles.
If in the future we will split the process so that every tile folder will have its own modification date then I'll think of a way to incorporate this in the attribution.
