### ISSUE TITLE
Could you add a description about how to use osm.org.il  tiles under marble ?

### ISSUE THREAD

**Issue by shtrb** [IsraelHikingMap/Map#29]
Could you add a description about how to use osm.org.il  tiles under marble ?

[This](https://github.com/shtrb/marble/) have the description and the necessary files to use osm.org.il tiles in [marble](https://marble.kde.org/install.php). 

credits to this projects already [included](https://github.com/shtrb/marble/blob/master/earth/osm.org.il/legend.html)

**Comment by HarelM** [comment]
I'm failing to understand your requirements. :-(
Can you give a little background on your project and better explain what you need from us?

**Comment by shtrb** [comment]
I'm asking if you can add a section for Marble in the IsraelHikingMap [readme file](https://github.com/IsraelHikingMap/Map/blob/master/README.md) a section that would describe how to use tiles stored at osm.org.il under marble (the is presented [here](https://github.com/shtrb/marble/blob/master/README.md)).

All needed information is already presented in the provided link.

Ideally support for osm.org.il configuration will be pushed into marble repositories (I'm working on that).
The repository I linked to store the needed files and setting , so one could use osm.org.il tiles directly with Marble (offline or online).

**Comment by HarelM** [comment]
Sure, Can you submit a pull request as I have no idea how to use Marble in order to add the explanation?
Please make it as "for dummies" as possible, the instructions on your project page were not entirely clear for me.

**Comment by shtrb** [comment]
done

**Comment by HarelM** [comment]
Pull request #30

**Comment by zstadler** [comment]
@shtrb,
The instructions are broken because [your mrble repository](https://github.com/shtrb/marble/) is no longer available.

**Comment by zstadler** [comment]
Marble instructions were removed.
