### ISSUE TITLE
0 M contour line

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#4]
0 m contour line appears offshore.
Not on Israel MTB map

**Comment by zstadler** [comment]
The MTB map avoids rendering the 0m contours everywhere, even on land.
For example , at http://osm.org.il/IsraelHiking/#/15/32.8727/35.4442

It may be possible to hack the contours SQL files and remove specific contour lines by elevation and bounding areas. This can be applied to the Mediterranean Sea, the Kinneret, and the Dead Sea.

**Comment by zstadler** [comment]
Use [SQLite Delete query](http://www.tutorialspoint.com/sqlite/sqlite_delete_query.htm) on the contour SQLite files generated by Maperitive.
1. Mediterranean Sea: `DELETE FROM Contours WHERE Elevation <= 0 AND (MinX-34.3)*3<(MinY-31)*1.4;`.
Applicable for contour files 34-31, 34-32, 34-33
2. Sea of Galilee: `DELETE FROM Contours WHERE Elevation <= -210 AND MinY>32.7;`.
Applicable for contour file 35-32
3. Dead Sea:  `DELETE FROM Contours WHERE Elevation <= -390;`.
Applicable for contour file 35-31

**Comment by zstadler** [comment]
Mediterranean Sea rule should also be applied to 35-33. 
For example, the Nahariya shoreline - http://israelhiking.osm.org.il/#/16/33.0006/35.0846
