### ISSUE TITLE
cycling specific features

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#40]
There are several tags that are important to MTBikers which are missing fro the map.
Especially important to tourists planning a bikepacking or touring trip of Israel.
Those are bike shops, water points, food shops and restaurants, gas stations and hotels.
The opencyclemap is a popular map to consult regarding these.

**Comment by zstadler** [comment]
This is an outdoors oriented map and for MTBikers in particular. As such, bike shops and water points seem to improve its usefulness.

On the other hand, I don't think adding food shops, restaurants, gas stations, and hotels would improve its usefulness for MTBikers. Instead it will turn the map into a general purpose tourism map and add a lot of clutter in urban places.

I have received an updated "rules" definition file for the MTB Map from @Reitstoen.
I plan to update the base map first and then work on bike shops and water points.

**Comment by HarelM** [comment]
Not sure the original rule file has a Github repository, but if so I would advise to open an issue there as well and if we decide to fix it add a pull request so that he'll benefit from it as well - which is the fundamental principle of open source... :-)

**Comment by valleyofdawn** [comment]
Its just that gas stations are prime sites to fill up water and pump up tires. If you worry about clutter add it only at high zooms. We can live without hotels.

**Comment by valleyofdawn** [comment]
At least take care of water sources. This can save a desert rider life.

**Comment by zstadler** [comment]
Some ions were missing from the MTB map, including drinking water.

**Comment by zstadler** [comment]
Remaining request: add [shop=convenience](http://wiki.openstreetmap.org/wiki/Tag:shop%3Dconvenience) .

May want to use the Mapnik icon - http://wiki.openstreetmap.org/wiki/File:Convenience-14.svg

**Comment by valleyofdawn** [comment]
I still can't see amenity=restaurant and shop=bicycle
for example here:
http://israelhiking.osm.org.il/#/?s=oxNgTXTf7q

**Comment by zstadler** [comment]
The fix was deployed to the site
