### ISSUE TITLE
MTB relations

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#41]
Would be very useful to add those. Much like OCM does.

**Comment by HarelM** [comment]
Can be better seen here:
http://www.opencyclemap.org/?zoom=15&lat=32.70084&lon=35.23553&layers=B0000

**Comment by zstadler** [comment]
we need to find a way to allow bicycle routes to co-exist with hiking trails.
This level of highlighting is so intense that is is currently used only for the Israel Trail.
Suggestions are welcome.

**Comment by HarelM** [comment]
We can use it only in the MTB map...?

**Comment by valleyofdawn** [comment]
Wide yellow semi-transparent color for LCN, Red for RCN, Blue for NCN. Only in the MTB map of course

**Comment by valleyofdawn** [comment]
Please prioritize this.
To me this is the most important feature holding back the use of the MTB map.
Circular routes maintained by KKL and others are extremely popular, as you can see in the Strava layer, There is no way to recognize them, especially the "track" portions, in your map.

**Comment by zstadler** [comment]
OK.
You can set the priority by adding a label: Critical/High/Medium/Low

**Comment by zstadler** [comment]
The highlighting is sometimes obscured by other marks.
For example, at the [Kanim single](http://israelhiking.osm.org.il/#/?s=aIDsUGlwY9):

![mtbTiles/14/9783/6671.png](https://cloud.githubusercontent.com/assets/1304610/15529578/002a2054-2257-11e6-8e01-4f847d83674b.png)
