### ISSUE TITLE
historic=tomb

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#45]
Use either ruins or archaeological icon for historical tombs (or use a different icon, which ever you think fits).
See here:
http://israelhiking.osm.org.il/#/15/32.6398/35.0684

Ancient burial cave was marked as archaeological site instead of historic tomb (which I think fit better to what is there).

**Comment by zstadler** [comment]
[historic=tomb tags](http://wiki.openstreetmap.org/wiki/Tag:historic%3Dtomb) can refer to any tomb, important or not. 

I think they are worth putting on our map only if they have [archaeological_site](http://wiki.openstreetmap.org/wiki/Tag:historic%3Darchaeological_site) or [monument](http://wiki.openstreetmap.org/wiki/Tag:historic%3Dmonument) importance.

**Comment by HarelM** [comment]
I know, I've placed 2 of them yesterday.
I haven't found a good way to map historic tombs though (besides using archaeological_site with the relevant name of ancient burial ground).
your thoughts are welcome.

**Comment by zstadler** [comment]
I suggest we close this issue as "wontfix" as the importance of the site is determined by other factors.

**Comment by valleyofdawn** [comment]
There is an icon named holy-place.png in the MTB icons floder that I use in the MTB map for that.
