### ISSUE TITLE
Add wget.exe to the installation instructions

### ISSUE THREAD

**Issue by mk4th** [IsraelHikingMap/Map#46]
Hi,
I tried to run the script and got an error

```
>use-ruleset` alias=default
Running the script 'C:\Temp\Maperitive\IsraelHikingMap\Scripts\Maperipy\CreateOruxMap.py'...
> change-dir dir="C:\Temp\Maperitive\IsraelHikingMap"
Warning: wget location not found. Could not add it to PATH.
Warning: WinSCP location not found. Could not add it to PATH.
Warning: Mobile Atlas Creator location not found. Could not add it to PATH.
=== Update israel-and-palestine-latest.osm.pbf ===
Executing program: wget.exe --timestamping --no-directories --no-verbose --directory-prefix="C:\Temp\Maperitive\IsraelHikingMap\Cache" http://download.geofabrik.de/asia/israel-and-palestine-latest.osm.pbf
Python error: Traceback (most recent call last):
  File "C:\Temp\Maperitive\IsraelHikingMap\Scripts\Maperipy\CreateOruxMap.py", line 58, in <module>
SystemError: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
READY
```

**Comment by HarelM** [comment]
This is probably due to the fact that you don't have wget and winspc.
We'll try to make the instruction better/the code more robust.

**Comment by zstadler** [comment]
The script uses wget to download the latest OpenStreetMap data.
wget for Windows can be downloaded from https://eternallybored.org/misc/wget/ and several other places.

I will fix the script to avoid running wget and/or MOBAC if they are not installed.

**Comment by HarelM** [comment]
Thanks, please notify the user what he needs to do in case something did not go well.
"Could not add to path" should probably say "Please install something, you can get it from somewhere.com"
