### ISSUE TITLE
Garmin instructions

### ISSUE THREAD

**Issue by mk4th** [IsraelHikingMap/Map#47]
Can you please add instructions for routable Garmin map?
There are instructions for and automatic tools for general OSM maps.
They need some adaptions to generate maps from the hiking map.
Thanks
Moshe

**Comment by HarelM** [comment]
Hi Moshe,
I'm not sure I fully understand the request.
The maps we are creating are tiles, which means that routing on them is done with OSM data like we do in our site, but this is technology dependent and each platform is doing it on its own - meaning we wrote a javascript site to do it for browsers and there is oruxmaps for android.
Can you elaborate more on what exactly you want to accomplish?

**Comment by mk4th** [comment]
The idea is to create sequence in order to generate *.img files for Garmin devices.
These are map files, not just routes or POI.
Currently, there are some tools for generating Garmin maps from OSM data. There are also some code lines for those who want to download their own map.
[Online tool](http://garmin.openstreetmap.nl/)
[Wiki page](http://wiki.openstreetmap.org/wiki/OSM_Map_On_Garmin)
The routing is an option that Garmin devices have. You don't need to pre-route the track. I think that routes are a layer on the map and the routing device is connecting the lines to create track.

The requirement is downloadable files (script is better) that will enable the map generation on user computer. Auto-generation (weekly? monthly?) on the server is great, but require some work from the server.

**Comment by zstadler** [comment]
From the sources above, and previous exploration of the subject, I concluded that 
* Garmin maps are created directly from the OpenStreetMaps data, not from a map like Israel Hiking.
* The specific formatting of the Israel Hiking map is created in a way that is incompatible with Garmin .img format. 

Note that the routing capabilities of the site are separate from the map itself and can also be used with any background.
