### ISSUE TITLE
IsraelHiking.xml

### ISSUE THREAD

**Issue by mk4th** [IsraelHikingMap/Map#48]
File is not under the downloaded master file.
I downloaded it from [here](https://github.com/HarelM/IsraelHiking/tree/master/OruxMaps)
I followed the path change instructions and created a copy under \mapsources. I can't see "Israel Hiking" on MOBAC.
[MOBAC 2.0.0 beta 1, build 2289]

**Comment by zstadler** [comment]
I will add the .xml file to the repository.

If you are getting a "The specified source folder does not exist" error, then please correct the directory path in the .xml file.
If you are not getting this error, please use another map source in MOBAC to navigate to Israel and zoom to level 7 or lower. If the tiles were created, you should be able to see the map.

**Comment by HarelM** [comment]
I have updated the reference to the tiles to be isrealhiking,osm.org.il/... instead of www.osm.org.il/IsraelHiking/... (in readme.md and in the file referenced by @mk4th) Please make sure to update the file before you add it.

**Comment by mk4th** [comment]
I wasn't getting any error, It just wasn't in the list.
I rewrite the file + did the navigation+zooming and now it is working.

**Comment by zstadler** [comment]
Resolved via 3593e69f0d1d13d857b73554ca7c58b08ebf9f82
