### ISSUE TITLE
Clutter 

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#5]
Please reconsider removing the clutter from lower zooms. Especially in densely mapped areas like the Jerusalem corridor it just looks bad and obstructs useful map info..
You can restrict spring names to higher zooms.

**Comment by zstadler** [comment]
Clutter removal cannot be done by area. Removing springs, for example, from zoom 12 will also make it difficult to spot them in the Negev.

I think that reducing the icon size for springs and wells in zoom 12 will reduce the clutter and keep them visible in less dense areas.

The Jerusalem area is also very cluttered. I plan to de-clutter by:
* Icons for Places of Worship: synagogs, churches, etc. should be removed from zoom level 13.
* Names of Places of Worship and Cemetery should be removed altogether from the map - http://osm.org.il/IsraelHiking/#/16/31.7764/35.2352
* Nature Reserves names should be shown by their size, similar to Forests.
* Names of both Forests and Nature Reserves should be further filtered to be shown for larger areas in each zoom level.
