### ISSUE TITLE
Add natural=flowers

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#50]
When there is a substantial presence.

http://overpass-turbo.eu/s/mLg

**Comment by HarelM** [comment]
I had an Idea to add "blooming" areas according to the date the map is created.
This way people can surf into the map and see areas with colors according to an area that is blooming. e.g. "Darom adom" in the spring, Tel shuja when there are Turmusim. Tel Shahar and Galed for Rakafot etc...
Adding those areas might be easy and can be expanded in the future to other places.

**Comment by zstadler** [comment]
The blooming period can be set using the [seasonal](http://wiki.openstreetmap.org/wiki/Key:seasonal) tag

**Comment by HarelM** [comment]
Seems like this tagging is not advised any more :-/ No wonder I had a hard time finding the OSM definition page...
http://wiki.openstreetmap.org/wiki/Tag:natural%3Dflower
http://wiki.openstreetmap.org/wiki/Talk:Proposed_features/Tag:natural%3Dflower

**Comment by zstadler** [comment]
The repository is not actively maintained after the transition to vector maps.
