### ISSUE TITLE
Fix route color (near Arad)

### ISSUE THREAD

**Issue by MatanBenMoshe** [IsraelHikingMap/Map#51]
The route here has the color red, not black and blue:
http://israelhiking.osm.org.il/#/?s=NWTb1GVg3e

**Comment by HarelM** [comment]
Please be our guest and open an account in OSM, after you do, go to the address you above and click on the edit in osm button on the right pane (the map with pencil button). Change the colour tag of the relevant part from blue to red and we will render the changes in a day or two.
In the links in the map there is a link to the osm community forum where you can see videos on how to edit the map.
We'll be happy to answer any questions you have 😁
Happy mapping!

**Comment by zstadler** [comment]
Note that map updates should not be done based on the official trail maps, or any other map, but rather based on the physical trail signs on the ground.

**Comment by zstadler** [comment]
This is a map data issue, not a map formatting issue.
As described above, the change needs to be done using one of the OpenStreetMap (OSM) editors, according to the OSM mapping rules.
