### ISSUE TITLE
Improve the altitude lines accuracy

### ISSUE THREAD

**Issue by MatanBenMoshe** [IsraelHikingMap/Map#52]
The altitude lines sometimes look not so accurate:

See this example when specific altitude line override itself:
http://israelhiking.osm.org.il/#/?s=Vy0HEO9TDR

**Comment by HarelM** [comment]
This is the best data we have, if you have a source of DEM that we can use for free please share...

**Comment by zstadler** [comment]
The algorithm that creates the contour lines is built into the software that creates the map.
In any data source there will probably be 8-shaped contours that may cause such an overlap.
I will look into tweaking the curve setting of contours and see if there is any improvement.

**Comment by zstadler** [comment]
The contour lines are already curved.
Unfortunately, there are no additional tweaking options.
