### ISSUE TITLE
Show hiking trails at all zoom levels

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#53]
While the hiking trails are the foundation of the Israel Hiking Map, hiking trails are not shown at zoom level 12 and below.

While adding the trails overlay to the map, I noticed it looks much more informative when hiking trails are shown at all zoom levels. 

For example, this is the expected map [at zoom level 8](http://israelhiking.osm.org.il/#/8/30.9847/34.5039?s=ET7o4Gicsu).

**Comment by valleyofdawn** [comment]
I suggest showing the trails at low zoom but as a uniform very thin line. The current result is ungainly in densely blazed areas.
