### ISSUE TITLE
Fragmented forest names

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#6]
Forest and nature reserve names should not be fragmented if these relations contain several areas. If this can't be solved I would lose forest names altogether. These are official KKL names based on nearest settlement names and nobody uses them in real life anyway.

**Comment by zstadler** [comment]
I partially agree. I think these names should appear for larger areas only in each zoom level.

**Comment by zstadler** [comment]
As a trial, I will double the size of the individual forest required to show at any zoom level
