### ISSUE TITLE
Elevation contours inside water

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#60]
It's ugly, please make sure the water covers them. Very prominent in seasonal water reservoirs.

**Comment by zstadler** [comment]
Can you add an example or two?
Don't you think that contours make sense when a seasonal reservoir is empty?

**Comment by valleyofdawn** [comment]
http://israelhiking.osm.org.il/#/16/33.0188/35.4594
http://israelhiking.osm.org.il/#/16/33.0344/35.1206

No, I've never seen it done in paper maps. We can decide on rendering for seasonal reservoirs.

**Comment by HarelM** [comment]
I don't see a reason to make an effort to remove them. I do find them helpful to know how deep a pool is. I also don't find them that ugly.
