### ISSUE TITLE
MTB Map cemetery icon

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#61]
Although funny I'm not sure this is the appropriate sign for cemetery.
![image](https://cloud.githubusercontent.com/assets/3269297/14884559/2eb9e4ae-0d4e-11e6-86bc-790d887d789a.png)
Also this icon does not appear in the MTB legend.

**Comment by zstadler** [comment]
What do you suggest, remove it? replace with what?

**Comment by HarelM** [comment]
Something like the following would do I think:
![image](https://cloud.githubusercontent.com/assets/3269297/14890496/92593150-0d6b-11e6-9d83-dc0b09c8d050.png)
Taken from www.map-icons.com.
I think we can also use this icon in the regular map not just the MTB map.
Also don't forget to add it to the legend.

**Comment by zstadler** [comment]
Unfortunately, Maperitive does not accept svg icons.

**Comment by zstadler** [comment]
![cemetery](https://cloud.githubusercontent.com/assets/1304610/14898472/98ca36d2-0d8f-11e6-9953-915bf84b92bd.png)

**Comment by HarelM** [comment]
Looks good.
