### ISSUE TITLE
MTB IL: Avoid label overlaps for areas

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#64]
Label density is controlled by the size tag, created by the `mtbmap.py` script.
To avoid the overlaps, running the script by `IsraelMTB.mscript` is temporarily disabled.

**Comment by Reitstoen** [comment]
Is there a way to "count" the number for outer loops of a multipolygon?
The problem with this script is that it calculate the size for the entire multipolygon, but Maperitive renders the name for each closed outer loop, meaning the "size" will be too large if there is more than one outer loop.
The AddWayLengthTags.py script is probably a better solution.

**Comment by zstadler** [comment]
Using AddWayLengthTags.py will address this issue. It will also require some minor changes to the rules, as the width provided is in Km and uses a different tag.

By the way, I have created a separate branch where I keep your updates - [mtbmap.no](https://github.com/IsraelHikingMap/Map/tree/mtbmap.no). It is a great help in merging your updates. It can potentially also serve you to merge some of my changes to your code.

**Comment by zstadler** [comment]
Addressed as part of #93.
