### ISSUE TITLE
MTB IL: hill-shading covers contour lines

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#66]
For example, [here](http://israelhiking.osm.org.il/#/?s=YL8c7uPaZ6):
![13331](https://cloud.githubusercontent.com/assets/1304610/16149156/7083de24-3497-11e6-9343-f0d8ea8d002e.png)

See also [a post on Maperitive forum](https://groups.google.com/forum/#!topic/maperitive/deHiuNICi_U)
and [this Israel Hiking Map commit](cd9bd519d2a9f883af50a7979e0c775b353f32da).

Adapting the above approach to MTB IL handling of rivers and streams can be:

* Lines except contours - 600 [default]
* Legend areas - 590
* Legend background - 580
* Grid labels - 560
* Grid lines - 550
* Water areas - 530
* Rivers - 528
* Streams - 526
* Contours - 520
* Bitmap foreground - 500 [hill-shading, cannot change]
* Fill textures except water areas - 400 [default]

**Comment by zstadler** [comment]
This issue does not exist in the [Norwegian MTB map](http://mtbmap.no/) - the baseline for the MTB IL map.

After discussion with @Reitstoen, it looks like the issue is caused by way the hill shading is created.

While the hill shading of the Norwegian map is build with
`generate-relief-igor intensity=1.6 color=#006 sample-rate=1`
the hill shading for the MTB IL map is taken from an image file built with
`generate-relief-igor intensity=6 color=#808080`.
The higher intensity makes the hill shading less transparent while the higher color settings make it more grey than black. Both differences make it harder to see contour lines below the hill shading.

**Comment by HarelM** [comment]
Can you post a screen shot with both shades in order to see how it looks?
I probably took the hill-shade code from a Maperitive example...

**Comment by zstadler** [comment]
MTB IL current settings - `intensity=6 color=#808080`:
<img width="128" alt="intensity_6_0_color_808080" src="https://cloud.githubusercontent.com/assets/1304610/16195641/41ef8da6-3703-11e6-90af-2ee1cbe68aa4.png">
 Norwegian MTB settings - `intensity=1.6 color=#006`:
<img width="128" alt="intensity_1_6_color_000006" src="https://cloud.githubusercontent.com/assets/1304610/16195917/542fa072-3704-11e6-8ebb-af6cf4262eb0.png">
Proposed setting by @Reitstoen - two layers of `intensity=1.0 color=#006`:
<img width="128" alt="intensity_1_0_color_000006x2" src="https://cloud.githubusercontent.com/assets/1304610/16196181/a8736d20-3705-11e6-8fa6-3ea2575660ee.png">
Default settings - `intensity=1.0 color=#000000`:
<img width="128" alt="intensity_1_0" src="https://cloud.githubusercontent.com/assets/1304610/16196209/cffa52d2-3705-11e6-8086-27b3829fada8.png">

Note that this is a very steep slope, used to demonstrate the conflict with the contour lines.

**Comment by zstadler** [comment]
I think so too, but I'm not sure about the blue tint - color=#0006.

**Comment by Reitstoen** [comment]
I would not use the color I'm using :)
I wanted to make it a little blue, to simulate the blue tint you have in
shadows in real life. But the color I'm currently using is too
blue/purple-ish. I guess #023 would be a better fit. Or just use a neutral
black as the last example.

Another tip is to find an area with both flat and steep hills, and try
different settings and combinations of the hill shading.
The two layer (or even 3 layer) trick will make the flat hills a bit more
intense, but at the same time make the steep hills less intense.
At least the contours looks good now :)
In my opinion this is the best solution.

regards
Ola Endre
