### ISSUE TITLE
MTB IL: missing icons

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#69]
Spring
Viewpoint
Trail info
Intermittent stream

**Comment by zstadler** [comment]
SJJB uses `convert` from [ImageMagick](http://www.imagemagick.org/script/binary-releases.php#windows) to create a glow effect.

The relevant [line from the Unix script](/twain47/Open-SVG-Map-Icons/blob/master/tools/generatepng.sh#L35) , adapted for ImageMagick 7.0 Windows syntax for creating `icon.glow.png` from `icon.png` is:

```
magick convertconvert icon.png  ( +clone -background "#ffffff" -shadow 8000x2-0+0 ) +swap -background none -layers merge +repage -trim icon.glow.png
```

**Comment by valleyofdawn** [comment]
and for batch operations you can use asterisks?

**Comment by valleyofdawn** [comment]
convertconvert not a typo?
