### ISSUE TITLE
IHM and MTB IL: tunnel railroad

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#74]
A railroad in a tunnel appears as if it's on the surface. See new railroad to Jerusalem.

**Comment by zstadler** [comment]
A better example is [this railroad junction](http://israelhiking.osm.org.il/#/16/31.3196/34.7940) north of Beer Sheva. It contains A tunnel and two bridges, for reference.

The new railroad to Jerusalem is not a good example, as it is under construction. Some of its segments are currently not mapped as such. Sections that are not show on the map once the mapping is corrected.

**Comment by zstadler** [comment]
Resolved by 1efc9fa4c5cdc51f0ca862e7f11787080169df46
Scripts updated in c636b38de8017878e1b35741d492df18793ddb71
