### ISSUE TITLE
MTB IL: Unclear overlap of restaurant and turist attraction

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Map#96]
When a restaurant is also tagged as a tourist attraction, the result is not very clear on the [MTB map](http://israelhiking.osm.org.il/#/16/30.9733/34.7756?baselayer=Israel_MTB_Map):
<img width="61" alt="2016-09-21 16_25_02-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/18712623/facd41bc-8017-11e6-8dc7-85b383d98bb0.png">

Also note the name duplication.

I suggest that the Attraction will not be rendered in this combination.

**Comment by valleyofdawn** [comment]
Will correct in next release
