### ISSUE TITLE
Add note / report a problem button missing

### ISSUE THREAD

**Issue by yrtimiD** [IsraelHikingMap/Map#99]
I see more and more people become familiar with this map, hence more people can submit corrections to the map.
Will be very nice to add "Add note" button as original openstreetmap.org has.

**Comment by HarelM** [comment]
Can you please open this issue again in the site repository? This repository is related to map styling and tiles generation while the other one is related to the map containing site.
I would like to continue the discussion there.

**Comment by yrtimiD** [comment]
Done.

**Comment by yrtimiD** [comment]
https://github.com/IsraelHikingMap/Site/issues/250
